---
title: "計畫書"
author: "(待補上)"
date: "`r Sys.Date()`"
bibliography: "1_literature/ref.bib"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 緒論

### 能理性剖析疫情資訊的認知動機因素

2020年春天全球爆發的新型冠狀肺炎疫情，不僅考驗世界各國的醫療資源負荷，也挑戰各國公衛措施因應新型傳染病蔓延的能力。公衛措施能發揮效用的重要條件是大眾對疫情狀況的正確認知，例如日常生活落實非藥物介入措施、接種疫苗的必要性等。一般人主動接收與個人生活密切相關最新資訊，以及評估資訊正確性等行動，一直是研究認知動機(cognitive motivation)的心理學者有興趣探討的課題。在此特殊的疫情時期，提供心理學者藉此機會探討一般民眾的個人認知動機因素，為何會傾向相信不真實資訊。本研究採取重製 @bootGatheringProcessingInterpreting2021 的研究假設與方法，探討有意願相信不實資訊或流言說法的台灣民眾，認知需求(Need for Cognition)與認知閉合需求(Need for Cognitive Closure)等動機因素，與傾向不相信不實說法的民眾之差異。

### 認知動機的定義、問卷開發概念

> 明翰：回顧認知動機的定義、問卷開發概念        


首先回顧認知動機的定義、問卷開發概念，國內運用認知動機問卷探討的主題及研究方法，各國研究者採用認知動機問卷探討民眾如何面對疫情的主題，研究期間台灣疫情資訊主題變化，說明如何透過認知動機評估問卷及訊息來源調查，預測一般民眾如何評估可觸及的疫情資訊正確性。





1. 認知需求(Need for cognition)

認知需求源自Cohen等人(1955)透過分組比較實驗所提出的概念，指出有高認知需求者傾向主動組織缺乏架構及模糊的資訊。累積後續各種領域的研究發現，Cacioppo等人(1984)主張高認知需求者喜歡思考，隨時有了解新知識的需要。合理推測高認知需求者會透過不同管道獲取資訊，並且判斷資訊的真實性。他們依此概念發展18題版本的認知需求量表，提供各領域探討個人判斷及評估資訊的研究者，做為衝量與調節認知因素的分析指標。中文版量表的開發者高泉豐(1994)曾參與Cacioppo等人(1984)的編製，成為台灣地區行銷與廣告研究領域探討民眾理解如何資訊的一項研究工具(楊朝明 & 周郁軒, 2013; 陳佳誼 & 柯書婷, 2016; 陳正男等人, 2005)。

<!---
自從Cacioppo以後，便開始也有很多學者定義認知需求，例如Durvasula, and Akhter（1990）將個人的認知需求定義為，處理廣告訊息的動機（Zhang and Buda, 1999），國內也有學者對認知需求定義，「表示個人對「建構關鍵情境為有意義與統整的形式」的需求高低，也就是將特定情境轉化為個人系統的需求，此需求強度是因人而異（周惠珍，1999）。


問卷來源文獻: @cacioppoNeedCognition1982;  @cacioppoEfficientAssessmentNeed1984

@bootGatheringProcessingInterpreting2021 使用 @cacioppoEfficientAssessmentNeed1984 18題版本

國內認知動機的問卷使用

過去的研究發現國內對於認知需求的研究有許多篇幅偏向行銷與廣告。而在國內認知需求問卷使用，有經由文獻回顧發現國內認知需求量表中譯版高泉豐(1994)，並透過瀏覽後證實此份針對問卷改良的文獻是Cacioppo(1984)的中譯版本，也在不少國內認知需求主題的相關研究被使用。另外在本重製研究透過文獻回顧找出國內外研究也有使用Cacioppo(1984)、高泉豐(1994)。
--->


2. 認知閉合需求(Need for cognitive closure)

<!---
問卷來源文獻: @kruglanskiPsychologicalTheoryTesting1997
--->

認知閉合需求是指為了理解不斷變動的資訊，個人付出認知資源的主觀意願(Webster & Kruglanski,1994)。Kruglanski等人認為認知閉合需求可分為兩種層次：其一是急迫性(urgency)，係指個人認為最先取得的資訊最為可信的程度；其二是持久性(permanency)，係指個人不會因為後續資訊而更新先前所知的程度。合理推測高認知閉合需求者傾向相信最先接收的資訊，並且不論最早資訊的正確性，不想理解後續的訊息(Thompson,Roman,Moskowiz,& Chaiken,1994)。運用Kruglanski等人開發的問卷，後續研究提出高認知閉合需求者的幾種特質，例如喜歡有秩序、明確且可預測性的事物，傾向保守的價值觀和遵守傳統(Crowson,Debacker,&Thoma,2006;Van Hiel,Pandelaere,& Duriez,2008)；偏好淺層的系統化思考(De Zavala, Federico,Cislak,& Oldersma,1999;De Dreu,2008)；依賴可行的捷思策略和經驗法則(De Dreu,Koole,& Okdersma,1999;De Dreu,2003)；以及習慣採取競爭而非合作的利己行為等(citation?)。

Kruglanski等人最早開發的認知閉合需求問卷(Webster & Kruglanski,1994)共有42題，從57條項目節選出來，題組評量向度包括順序(Order)、可預測性(Predictability)、果斷性(Decisiveness)、歧義(Ambiguity)、封閉性(Closed Mindedness)。Boot等人(2021)使用的認知閉合需求問卷是增加5道測謊題的後續版本[@kruglanskiPsychologicalTheoryTesting1997]。然而與Boot等人相同時間進行的疫情心理學研究，大多使用Roets與Van Hiel (2011) 開發的15題版本，這個版本是Roets 與 Van Hiel透過反覆篩選Kruglanski等人的題本，從每個向度挑出鑑別度最高的3個問題所構成。


<!---
@bootGatheringProcessingInterpreting2021 使用 @kruglanskiPsychologicalTheoryTesting1997 47題版本
--->

### Boot et al.(2021)的研究假設及發現

以招募至少500位參與者，Boot等人對於認知需求及認知閉合需求評分有明顯差異的四組參與者，預期對於疫情資訊的接收與判斷有以下假設及發現：


假設1. 因為高認知需求者更喜歡思考的歷程，他們在意的是思考帶給他們的樂趣，而不完全是為了解決問題或得到結果。因此Boot等人假設相對於低認知需求者，高認知需求者對於疫情(a)有較多的正確知識，(b)較常更新疫情資訊，以及(c)更依賴由可查核消息來源的訊息管道獲取最新疫情資訊。研究結果顯示認知需求評分與真實疫情資訊的確信程度有明顯正相關，但是與流言說法的確信程度有明顯負相關；認知需求評分與參與的搜索疫情訊息頻率無明顯關係，不過描述性分析顯示多數參與者會主動搜尋；集群分析(cluster analysis)無法從認知動機問卷評分、疫情資訊確信度、以及媒體使用狀況調查等調查資訊，區辨高認知需求動機者獲得疫情資訊所偏好的媒體管道。因此研究結果只有支持高認知需求者有較多正確知識的假設。

<!---
假設一包含三個部分:假設H1a: 高NC者對疫情的正確認識高於低NC者，H1b: 高NC者更新疫情資訊的頻率高於低NC者，H1c: 高NC者依賴新媒體及可靠管道獲取最新疫情資訊來源的程度高於低NC者
從過去的研究可以看見，NC高的人更喜歡思考的歷程，他們在意的是思考帶給他們的樂趣，而不完全是為了解決問題或得到結果。原始研究透過前調查北卡羅納州參與者，發現偏於高NC思考的人，他們會更加地想去理解疫情資訊。在媒體資訊來源方面，原始研究指出傳統的傳播媒體，由於涉及普遍性，適合所有觀眾收看，因此來源相較於社交網絡媒體傳播的訊息，會更為客觀。研究者認為高NC者會傾向接收傳播媒體，並透過電視提供的訊息當作是一種資料判別的方向，進而去瀏覽社交媒體的其他疫情資訊。

對於認知動機為NCC者的假設
--->
假設2. Boot等人預期高認知閉合需求者對於自認為是真實的資訊，不論是否為事實會有較高信心。然而結果顯示高認知閉合需求者對於真實資訊的信心評估明顯高於低認知閉合需求者，兩者對於流言說法的信心評估則無明顯差異。Boot認為認知閉合需求問卷無法區分參與者的信心評估是根據符合急迫性的資訊，還是形成持久性的資訊。在疫情剛爆發時期，資訊變動頻繁，不論參與者的認知閉合需求程度，都難以判斷各種謠言及陰謀說法的真實性。

<!---
高NCC者比低NCC者對個人認為是真實的資訊更有信心
認知動機為NCC的人，會傾向思考是為了要解決問題，對於接收到的資訊，也會出現凍結資訊的現象。原始研究也提及，NCC的人會將接收到認為是可靠的資訊固化了某種他們自己覺得足以解決問題，或者能夠對於大環境不確定性值的狀況加以有個內心的標準。因此高NCC者對於資訊的正確程度，資訊是否真實，高NCC者更相信自己所接收到的資訊為真實。

陰謀論與認知動機的考量
--->

假設3: 低認知需求且高認知閉合需求者有最低的認知動機，這類人士不喜思考又希望有最快或最穩定的答案，Boot等人預期這類參與者對流言說法的確信和會高於有較高認知動機的參與者，包括高認知需求且高認知閉合需求者、高認知需求且低認知閉合需求、以及低認知需求且低認知閉合需求者。而Boot等人的迴歸分析顯示認知需求與認知閉合需求的交互作用迴歸係數，無法解釋流言說法的確信度變異。


<!---
低認知動機者(低NC,高NCC)容易接受流言說法  
原始研究在假設一有提出傳統媒體之外的網路社交媒體可能接觸到更多沒辦法客觀證實的資訊。而在原始研究對於陰謀論的看法則提出「陰謀論本身能夠為大流行複雜問題提供現成答案」，等藉以減輕不確定性。原始研究假設資訊來源以及陰謀論的接受程度也與認知動機是有關聯的情況下。因此對於高NCC容易接受陰謀論的資訊，也許成立，對於NCC者來說，能夠解決問題，對於環境帶來的大事件有個依準。另外對低NC者也許更新疫情資訊頻率低，也可能導致在瀏覽網路平台時，更有機會接收陰謀論的說法。而研究分為四組，其中將同時包含兩種認知動機，但卻更傾向於接受陰謀論資訊的這組，可能更符合研究想看到的結果。
--->



| Boot et al.(2021)原始假設                                           | 結果支持狀況 |
|---------------------------------------------------------------------|--------------|
| H1a: 高NC者對疫情的正確認識高於低NC者                               | 充分支持     |
| H1b: 高NC者更新疫情資訊的頻率高於低NC者                             | 不支持       |
| H1c: 高NC者依賴新媒體及可靠管道獲取最新疫情資訊來源的程度高於低NC者 | 不支持       |
| H2: 高NCC者比低NCC者對個人認為是真實的資訊更有信心                  | 部分支持     |
| H3: 低認知動機者(低NC,高NCC)容易接受流言說法                        | 不支持       |



<!---
@bootGatheringProcessingInterpreting2021 使用 @kruglanskiPsychologicalTheoryTesting1997 47題版本

### 台灣的認知動機研究

> 明翰：台灣學術圈使用NC或NCC問卷，探討資訊解讀或認知態度的研究主題

國內使用認知需求的研究:

國內對於認知需求主題相關的文獻涉及消費者以及廣告方面，廣告的介入(曾忠蕙， 王又鵬，民國95年)，將行銷手法中小額建構方式以及總額建構方式的行銷手法呈現於商品中。對於消費者而言「小額建構方式下所貶值的損失金額比較小」，研究結果發現小額建構方式更使消費者買單，研究將認知需求當作中介考量。發現消費者的認知需求程度會影響購買行為。

目前我們可以知道，在國內與認知需求相關研究，主要以行銷以及廣告兩者主題較為研究的方向。而其中，廣告的相關研究中，(陳正男，丁學勤，林素吟，劉若蘭，2005)將認知需求當作考量藉此衡量廣告效果。透過問卷調查發現，高認知需求的人傾向於接觸負向訊息以及理性的訊息來源；反之低認知需求的人反而偏好症項訊息，以及感性的訊息來源。

這與Boot(2021)的研究雖然探討項不同，但也許可以延伸高認知需求者，對於接收訊息的普遍程度。他們更為注重接受訊息，喜歡思考的歷程 Wolf(1955)。也許運用在觀看廣告時，也因為高認知需求的思考方式，較不會排斥各類型廣告效果，因此他們更有機會接觸每種不同的廣告，並較不會受到某特定類型的廣告吸引。對於喜歡接收訊息的他們可能更傾向閱覽完廣告效果後，選擇自己所感興趣的廣告效果。Boot(2021)在研究假設中認為，高認知需求者使用社交網路平台的管道更勝於低認知需求者，在問卷調查分析後仍然拒絕上述假設。透過對於兩者的研究者同樣對認知需求的介入，也許可以假設，高認知需求者，他們喜歡接收訊息，並從中判斷訊息的可信程度，或是他們平日的思考習慣，喜歡先理解全部的訊息。然後再來選擇自己有興趣的資訊或信任的資訊。因此也許某種程度而言，他們也許並不在意要透過哪多少的社交網路平台去理解資訊，而是在接收資訊時，可能花更多時間或更頻繁的去理解訊息。

認知需求與資訊解讀之相關研究: 閱覽文獻時，在許多適合台灣使用的搜尋引擎(谷歌、科技部人文社會中心、國家圖書館文獻查詢網、慈濟大學圖書館電子資源)均可以透過單一的關鍵詞查詢到許多文獻，但就目前疫情而言，國內的研究則注重疫情間的教育，例如遠距離教學(羅方吟，陳政煥，2021)，目前尚未有認知需求與資訊解讀為主題探討的研究。國外的部分仍然有探究互聯網使用與認知需求Kaynar a, Yair Amichai-Hamburger(2008)，


雖然並非與Boot(2021)使用相同的問卷，但是透過因素分析結果發現，高認知需求的者相對於低認知需求者更傾向用更多時間使用網路，且研究還發現，在皮爾森相關分析中，高認知需求者使用網路的目的偏向於互聯網提供之專業信息服務

國外認知需求與媒體使用相關研究:
(1)
國外的部分仍然有探究互聯網使用與認知需求Kaynar a, Yair Amichai-Hamburger(2008)，雖然並非與Boot(2021)使用相同的問卷，但是透過因素分析結果發現，高認知需求的者相對於低認知需求者更傾向用更多時間使用網路，且研究還發現，在皮爾森相關分析中，高認知需求者使用網路的目的偏向於互聯網提供之專業信息服務。
(2)
這是一個中國在線調查，屬於網路研究，Yan Su(2021)等人進行一項來自中國的在線調查 (N = 731)，並研究了中國和國際社交媒體使用對 COVID-19 陰謀論認可  (CTE)的條件性間接影響。其中裡面有提及認知需求程度的不同可能也是一個間接影響陰謀論認可的原因。
 假設共有四個以及三個研究問題。其中研究假設四則提到，參與者認知需求的程度是否會影響陰謀論的支持。
 並無使用與Boot(2021)相關的問卷
(3) 
NFC(認知需求)與主流新聞曝光的探討，研究目的是想知道以認知需求為中介變項的介入，和主流媒體懷疑與主流曝光的關係。Yariv Tsfati(2005)et.al等學者在這份研究提及三個假設。
研究假設:
假設1: 主流媒體懷疑與主流媒體曝光降低互有關係。
假設2: 認知需求將與主流媒體曝光有正相關。
假設3: 新聞媒體的懷疑在影響主流新聞媒體曝光時會與NFC互動。  NFC水平高的媒體懷疑的影響會減弱，NFC水平低的媒體懷疑的影響會更強 --->


### 疫情情間的認知動機研究

為了更深入了解如何運用認知動機問卷，以及探討Boot等人的假設未獲支持的可能因素，以整理同時期四篇使用認知需求或認知閉合需求問卷的國外研究。


<!---本研究重製 @bootGatheringProcessingInterpreting2021 的問卷調查及假設分析，探討台灣地區民眾相信正確及錯誤疫情資訊的認知動機因素。

> 采妤：疫情爆發後，全球使用NC或NCC問卷，探討民眾應對疫情資訊及措施的態度或動機研究

()

（綜合）Roets & Van Hiel, (2011) 15題版與 Kruglanski et al. (1997) 47題版差異
--->


<!---防疫自我意識--->
@PingXuPandemicOfCOVID-192021 調查美國成年人保持社交距離和戴口罩的態度，與三種認知特質的關聯性，包括認知需求、自我控制以及風險態度（Casey，2015；Mohammed & Schwall，2012；Tittle等，2003）。其中高認知需求者較常表現需要耗費較多認知資源的自我控制行為（Cacioppo et al., 1984），個人對於誘惑有較高的抗拒力，願意追求長期利益(Stillman et al., 2017)。研究也顯示風險態度與自我控制有正相關，自我控能力越高，風險態度會傾向考量決策背景和決策結果。這項研究結果顯示民眾實踐社交距離和戴口罩的參與度，與自我控制及認知需求有明顯正相關。風險態度則與防疫行為無顯著相關，研究者推測可能是因為每人身處的所在地風險程度不同，風險態度受外在因素的影響並未在問卷回答上表現。


<!---環境環保--->

@briziHaveEnoughFood2021 探討認知閉合需求程度不同的民眾，對於浪費食物如何破壞環境的看法差異。這項研究詢問參與者是否會因為想減少疫情引起的不安全感而囤積大量食物，以及進一步導致資源浪費的看法。研究結果顯示，高認知閉合需求的參與者，越傾向囤積食物。研究者認為這種過度浪費資源的行為，是一種個人主義的表現。研究結果也顯示低認知閉合需求的參與者，傾向採取合作與維護共同利益的環保行為。研究者也提出建議，散佈安慰訊息安撫高NCC群眾，能有效運用資源。

<!---疫苗研究--->

奧地利學者透過政府支持的調查計畫，探討民眾對於施打疫苗猶豫的因素，其中包含居住地、就學程度、政黨支持度和認知閉合需求等[@EvaCOVID-19VaccineHesitancyInAustria2021]。研究結果顯示，不論是對疫苗沒有猶豫，還是對疫苗抱有中度甚至高度疑惑的民眾，彼此之間的人數比例並無差異。根據這項研究結果，研究者建議提昇疫苗施打率的任何措施，不必特意採取安撫低認知閉合需求者的策略。這項研究也發現，參與選舉投票的意願與對疫苗猶豫程度有最高相關性，沒有投票者與對疫苗猶豫者有許多類似特徵。

<!---陰謀論--->

疫情之前已有研究指出無法容忍不確定性的人士，更傾向相信陰謀論（Farias & Pilati,2021；Marchlewska 等人,2018；van Prooijen & Jostmann,2013），@VukašinCOVID-19conspiracy2021 探討疫情期間出現的陰謀論，是否容易被低認知動機者接受。他們的調查變項包括認知動機、存在動機及社會動機等三種可能會吸引個人接受陰謀論的心理動機(Douglas, 2021; Douglas et al., 2017)。@VukašinCOVID-19conspiracy2021調查的認知動機除了認知需求閉合，另一個是與陰謀論形成背景有關的幻覺模式感知(IPP, van Prooijen 等人，2018年；Whitson & Galinsky，2008年)。存在動機是控制需求，社會動機則是假定為不明顯的內部群體積極想法。研究結果顯示，這些心理動機雖和非疫情的陰謀論接受程度有些許相關性，但是與疫情期間形成的陰謀論接受程度沒有直接相關。


(討論Boot等人的假設未獲得假設支持的可能原因)


> 研究主題牽涉個人生活狀態的程度

> NCC問卷尚未能區辨高認知閉合需求來自急迫性或持久性

> Boot的施測時機疫苗尚未問世，還未出變種病毒，參與者尚未形成持久的看法

> Prolific平台的多數參與者年輕(20y\~40y)，會主動吸收最新資訊。 

> Boot等人採用的流言並非被長期流傳。

(重製研究的可行性)


原始論文中的假設 H1a：高NC者對疫情的正確認識高於低NC者，結果顯示為「充分支持」，原始研究也發現不只高NC者對疫情資訊的知識與信心顯著高於低NC者，高NCC者也與疫情資訊呈正相關，他們也發現，在疫情資訊題中，對真實資訊呈現的題目表現出更高的準確性，原始論文的給出的解釋為對不實資訊，回答"我不知道"，在理智層面上是屬於誠實回答的部份，因此偏向回答"我不知道"。[@suWhoEndorsesConspiracy2021] 我們在設計疫情資訊題目時，除了按照原始論文的設計外，我們有對疫情資訊做更新，並加入符合時事的疫苗題，題目部份也進行再三確認，預期也會達到顯著的效果。所謂高NC者，也就是較喜歡思考、較喜歡解決複雜的問題，在解決問題時較會注重過程中的人，反之低NC者則相反。[@suWhoEndorsesConspiracy2021]所以我們預期高NC者在接收到疫情資訊時，會去思考這些資訊為什麼會導致這結論，也可能去思考、查證疫情資訊的正確性或是來源可靠性，在這其間會比低NC者獲取更多並較正確的疫情資訊，所以高NC者對疫情的正確認識就會高於低NC者。

原始論文中的假設 H1b:高NC者更新疫情資訊的頻率高於低NC者，結果顯示為「不支持」。原始論文使用回歸分析發現 NC 與 COVID-19 相關訊息的搜索頻率並無關係，描述性分析表明，大多數人都會主動搜尋 COVID-19 的相關訊息。 在我們重製的研究中，由於我們是在台灣地區收集樣本，考慮到自從疫情爆發以來，每天都會有中央流行疫情指揮中心的記者會，因此推測大多數人每天至少會有一次更新疫情資訊的機會，所以可能也無法達到顯注差異，我們推測可能NC高低對危機資訊的更新頻率就較無相關，反而與政府的宣導力度有關。如果政府的宣導力度不會影響或者是不夠強力，我們預期在這項假設達到顯著。

原始論文中的假設 H1c: 高NC者依賴傳統媒體及可靠管道獲取最新疫情資訊來源的程度高於低NC者，結果顯示為「不支持」，原研究者假設傳統媒體（報紙、廣播、電視）比社交媒體更有可能經受住嚴密的審查。也有國外的研究顯示，傳統媒體通常會有更客觀的新聞報導，而社交媒體通常包括小報新聞和非官方來源，它們往往有更多聳動的標題與內容，社交媒體用也被證明比真實新聞更快、更廣泛地傳播假新聞。因此原始研究假設，高NC者更可能使用傳統媒體。但結果就跟H1b一樣並不支持，可能是收集到的樣本未能顯著，原始研究並未多做解釋。[@suWhoEndorsesConspiracy2021] 我認為社交媒體確實有上述的隱憂，傳遞假資訊的速度可能更快、更廣泛，但我覺得這要回歸回始用者如何組成他的社交媒體圈，有些社交媒體帳號也會分享正確且客觀的資訊，況且現今獲取新媒體的方便性遠高於傳統媒體。 該假設不支持主要是因為傳統媒體並沒有很頻繁的使用，對於這部分我們也認同，雖然傳統媒體審查嚴謹，符合客觀事實，較少出現假訊息，假新聞等等。但是因現在每人人手一機，相較於傳統媒體，手機網路是或許資訊更快速便利的方式，即使缺少傳統媒體的客觀性與嚴謹性，人們依舊傾向使用新媒體作為獲取資訊的工具，因此該假設雖然較難成立，但能用不同的方式去思考，對於新媒體是否有客觀性不應該一概認為比傳統媒體來的不客觀，在台灣有些新聞網站是比較有公信力，對於客觀性程度可能與報紙相同，所以我們認為傳統媒體與新媒體不太能去比較，如果單就分析可靠管道上，或許能夠支持此項假設。[@suWhoEndorsesConspiracy2021]

原始論文的假設 H2: 高NCC者比低NCC者對個人認為是真實的資訊更有信心，結果顯示為「部分支持」，確實高NCC者比低NCC者更傾向於回答"我確定這是真的"，但原始研究的研究者們進行推論分析，覺得無法斷定這種影響是由判斷信心、判斷準確度或兩者皆有所引起的，他們也表示未來的研究設計應該要想辦法分離這兩種概念。[@suWhoEndorsesConspiracy2021] 高NCC者，在面對到外界資訊的刺激時，會傾向確信第一個遇到的答案，並相信這資訊不去變動，會喜歡簡化理解到的第一手資訊，在思考的過呈中看重結果，而較不著重思考歷程。（黃瓊億，2010）由上述可知，因為高NCC者會有急迫性與持久性，所以在遇到資訊時會比低NCC者更有信心。我們也預期我們的假設會達到同樣的效果，而在原始研究的建議部分，我們的研究設計並未做太大的更動，我們更新了疫情資訊，也確認了疫情資訊題目並無問題，所以我們期望藉由時事題目，可以降低高NCC者在回答時受判斷準確度的比率。

原始論文的假設 H3: [林子渝] 低認知動機者(低NC,高NCC)容易接受流言說法，結果顯示為「不支持」，在原始文獻中研究者認為高NCC比較容易接受流言說法原因是：大多數高NCC的人為了減少資訊的不確定性更可能傾向支持有關流言說法的言論。但同時他們也認為低NC比較少去主動獲取有關疫情的資訊，所以認為高NCC與低NC比其他組更有機會去接受流言說法。在最後蒐集完的結果發現NC、NCC與流言說法拒絕都呈現正相關，並且也證實兩者間並沒有產生交互作用，顯然是不支持原研究者們的假設，研究者列出可能的原因是流言說法過於誇大，以至於多數人會判斷是虛假訊息，也可能是會接受流言說法的參與者較少，在原始研究中只有14%的參與者在第一波與第二波都支持至少一種陰謀論，樣本偏少，不易測出差異。[@suWhoEndorsesConspiracy2021] 原研究的假設可能受到參與者對題目理解的不同，或是多數參與者的宗教政治立場較開放，使得較少參與者去接收流言說法。對於H3的重製我們把原本關於冠狀病毒的流言說法8題修改為冠狀病毒4題與疫苗資訊4題，為了更容易使我們的流言說法題目讓低認知動機的參與者接受，我們傾向蒐集近期在網路上或各大論壇所談論的資訊，這些資訊都是目前並沒有得到證實，而流言說法都是針對中國大陸所提出的，因台灣比起播報其他國家的流言說法更喜歡播報有關中國大陸的流言說法，所以對於如果有在關注這些事件的參與者而言，可能比較容易去接受這些說法。 [張祥偉] 在原始文獻中研究者認為高NCC比較容易接受陰謀論原因是：大多數高NCC的人為了減少資訊的不確定性更可能傾向支持有關陰謀論言論。但同時他們也認為低NC比較少去主動獲取有關疫情的資訊，所以認為高NCC與低NC比其他組更有機會去接受陰謀論。在最後蒐集完的結果發現NC、NCC與陰謀論拒絕都呈現正相關，並且也證實兩者間並沒有產生交互作用，顯然是不支持原研究者們的假設，研究者列出可能的原因是陰謀論過於誇大，以至於多數人會判斷是虛假訊息，也可能是會接受陰謀論參與者較少，在原始研究中只有14%的參與者在第一波與第二波都支持至少一種陰謀論，顯然樣本偏少，不易測出差異。對於H3的重製，我們盡量限縮陰謀論的訊息，也就是把新聞、報紙常常播報的陰謀論放進去我們的測試題目中，並且把原本關於冠狀病毒8題修改為冠狀病毒陰謀論4題與疫苗資訊陰謀論4題，放在我們的題目中，驗證原研究者假設的出發點或許沒有錯，可能受到參與者對於題目的理解，或是多數參與者的宗教政治立場較開放，使得較少參與者去接收陰謀論於是想放在與原研究不同國家中可能產生不同的結果，為了使我們的陰謀論題目讓參與者更容易接受說法，我們傾向蒐集近期在網路上或各大論壇所談論的資訊，這些資訊都是陰謀論目前並沒有得到證實，而台灣的陰謀論都是對中國大陸所提出的，因台灣比起播報其他國家的陰謀論更喜歡播報中國大陸的陰謀論說法，所以對於如果有在關注這些事件的參與者而言，可能比較容易去接受這些說法。[@suWhoEndorsesConspiracy2021]


### 台灣地區疫情資訊主題變化

> 祥偉、子渝：從目前學術機構或民調中心的資訊，整理台灣社會疫情資訊的樣態; 民眾對疫情資訊的信任度調查

(2020剛爆發時 vs. 2021五月至今 大眾媒體的疫情資訊主題變化) 4: 2021年5月24日-2021年5月27TVBS民意調查 詢問民眾接種疫苗的意願 8: 台灣民意基金會於2021年8月16日到8月18日 詢問民眾接種疫苗的偏好

(台灣民眾接種疫苗意願調查) 資料來源：TVBS民意調查中心。新冠肺炎疫情與民眾疫苗施打意願網路民調

在重製研究的過程中，我們更改原文獻的研究材料放入疫苗資訊作為新題目，因台灣許多媒體或組織都有做疫苗施打的民調，為了避免有政治干預的媒體對民調有影響，我們盡量挑選符合中立的媒體與非政府組織的民調，在TVBS網站中，訪問時間為2021年5月24日-2021年5月27日。訪問方法為網路問卷SurveyCake平台。回收有效問卷為455104位20歲以上台灣民眾。在問卷設計上，有二個題目方向是關於我們的問卷設計，分別為：

1.  未來如果開放全民施打新冠肺炎疫苗，請問您會不會去施打新冠肺炎疫苗？有87%(394412人)表示會施打
2.  詢問參與者若政府購買中國代理商輝瑞BNT疫苗意願施打調查。有80%(361566人)表示會施打。

透過這兩個數據我們知道若有疫苗是幾乎都會願意施打，但在中國代理BNT的意願似乎沒有高過於前者。可見對於疫苗的種類上人民依舊會有疑慮。

(台灣民眾接種國內外疫苗意願調查) 資料來源：台灣民意基金會。 為了找尋資料來了解在疫苗選擇不單單只是選擇一種疫苗這麼簡單，往往有許多的考量例如副作用、保護力、剩餘劑量、政治因素等等，這些都會影響著我們對於疫苗的選擇，但在疫苗這麼缺乏的期間，有時候可能不顧是否會有很嚴重的副作用依舊會選擇有疫苗就打的狀況，台灣民意基金會於2021年8月16日到8月18日做了電話調查。有效樣本為1078人年齡為20歲以上。其中在國內外可供選擇疫苗偏好調查中，有一項問題為如果可以自由選擇疫苗情況下AZ、莫德納、BNT、高端會優先選擇哪一種？結果發現有40.9%莫德納、23.8%BNT、11.3%高端、9.5%AZ。而基金會更進一步地問如果能有第二個選擇會選？結果發現33.9%莫德納、24.3%AZ、22.3%BNT、6.7%高端。如果把兩個結果發現結合莫德納的比例是位居第一而高端是位居最後。造成這樣的情況，有幾種可能原因為莫德納的副作用比較少出現死亡個案，而高端有些民眾認為有政治干預，比較不信任，也有可能媒體大肆宣傳高端的陰謀論導致一般民眾對於接種高端就產生許多疑慮。

(2021五月至今 大眾媒體的疫情資訊主題變化) 結合民調發現從5月開始台灣大眾媒體主要在意的是疫苗的動向，以及疫苗的政策，在還沒爆發疫情時，普遍只在關心冠狀病毒的動向與其他國家所發生的疫情，在五月的時候台灣的疫苗政策還沒那麼積極，而日本注意到台灣的疫苗採購速度沒這麼快，就贈與台灣AZ疫苗，加上其他國家有注意到台灣的情勢，都有贈與給台灣多的疫苗，在五月中旬媒體比較關注的是BNT的採購，當時對於BNT的購買政策如果向中國的BNT代理商，購入的速度一定非常快，但因為台灣政府對於兩岸的局勢有所關心，所以堅持不購買中國的BNT疫苗，而TVBS在5月發出的網路民調，有幾題是想了解民眾對於政府採購中國的BNT意願調查，幾乎八成左右是支持購買，但政府的態度依舊堅決，在媒體上也是不斷吵。到了5月底台灣政府與高端疫苗和聯亞疫苗簽約一千萬劑的合約，在當時媒體所報導的是，在沒有完成二級試驗的狀態下，高端的疫苗是否有保護力依舊是未知數，人民認為是故意炒作股票等等陰謀論的出現，而到了8月，高端也成為台灣第三支可以施打的疫苗，在8月疫情已經逐漸趨緩，但是疫苗上依舊不足，截至2021年8月23日，能夠施打疫苗的種類只有AZ、莫德納、高端，疫苗接種率約為40%(衛生福利部疾病管制署，2021)。在許多人接種第一劑的同時需要擔心第二劑是否可以打到，否則過了期限，就等於要重打一次。



## 方法

### 研究程序與材料

問卷施測程序比照@bootGatheringProcessingInterpreting2021 ，參與者依序回答的四份問卷內容為： (1) 疫情資訊可信度評估共有32項，內容見後敘； (2) 人口背景資訊調查： 包括年齡、性別、居住地區是否為台灣、日常使用語言、教育程度、以及職業別；(3) 媒體使用狀況調查：包括有無使用或最常使用的網路媒體平台、日常使用網路時間、獲取最新疫情的資訊來源、情境、更新頻率、以及獲取最新資訊的動機；(4) 認知動機問卷：包括中文版認知需求問卷[@gaoquanfengRenZhiXuQiuDeGaiNianYuCeLiang1994]與認知閉合需求問卷[改編自 @AL:U0001-1907201017124300]。問卷設計與部署以網路實驗平台Psytoolkit準備及執行[@stoetPsyToolkitNovelWebBased2017]。

疫情資訊題目一共有32題，分別為12題真實資訊，12題不實資訊，8題陰謀論，使用李克特5點量表，從"1.我確定這不是真的"到"5.我確定這是真的"。由於原始研究的執行期間為2020年，部分疫情資訊已經過時，而且民眾重視的議題也有變化，並不完全適用於本研究預定收集資料的真實狀況。本研究收錄的真實資訊與不實資訊項目，各有6題替換為疫苗資訊相關的題目。為了避免設計題目沒有證據支持，我們的題目都是參考台灣事實查核中心、台灣內科醫學會網路學誌測驗、衛生福利部疾管署、臺大醫院家庭醫學部《COVID-19知識就是力量》等可查核的資訊來源，流法說法參考來源來自台灣事實查核中心與網路新聞平台收集的資訊。設定好的題目再交由推廣媒體識讀的志工團體協助評估，評估條件是任何一題圈選正確選項的協助者人數比例達到80%。任何一題的評估如果沒有達成上述條件，則會修改或重新找題目。

人口背景調查及媒體使用狀況調查項目題型設計都與@bootGatheringProcessingInterpreting2021的題本一致，除了部分題目的內容配合施測對象進行調整。由於本研究預定只在台灣地區施測，人口背景調查有關居住地區的問題，只有“台灣、澎湖、金門或馬祖等地區”與自填欄位；有關語言的問題，改為"中文"、"台灣地區各種方言(閩南、客家、原住民語)"與自填欄位。經常使用的網路媒體平台調查項目，調整部分台灣地區較少見的平台名稱，改為台灣地區民眾比較熟悉的平台，包括"噗浪/Plurk"，“狄卡/Dcard，“維基百科/wiki pedia“，“ptt/批踢踢實業坊“，“Google meet“，“LINE“，“方格子“。


認知動機問卷的認知需求採用 @gaoquanfengRenZhiXuQiuDeGaiNianYuCeLiang1994編譯並建立中文常模的18題版本。認知閉合需求問卷採用@AL-U0001-1907201017124300翻譯並測試的42題版本，[我們再將 @kruglanskiPsychologicalTheoryTesting1997 設計的5項測謊題中譯版置回，以求符合 @bootGatheringProcessingInterpreting2021 。]

### 研究參與者估計

由於研究程序是重製 @bootGatheringProcessingInterpreting2021 的第一波研究，以認知需求問卷與認知閉合需求問卷的回應事後分組，為使人數達到能鑑別假設預測的規模，本樣研究同樣預訂招募500位受測試者。

<!---
### 研究程序
<<<<<<< HEAD

1.  確認重制研究題目
2.  編制研究問卷
3.  確認分析計畫
4.  相關文獻探討
5.  收集資料
6.  分析與討論
=======
1. 確認重制研究題目
2. 編制研究問卷
3. 確認分析計畫
4. 相關文獻探討
5. 收集資料
6. 分析與討論
--->


## 分析計畫

(原研究第一波分析) 1. 疫情資訊回應資料的分類檢測：隨機選取200位參與者的資料進行確證性因素分析，分解兩種因素：Knowledge, Conspiracy Rejection

2.  確設性假設分析

檢測資料符合有Knowledge, Conspiracy Rejection的迴歸式之程度。

(Q1 Knowledge, Conspiracy Rejection分別分析) model 0: Q1 responses \~ 1 model 1: Q1 responses \~ NC X NCC

-   H1a: 迴歸分析確認高NC者掌握資訊的正確度高於低NC者

(只分析Q1 Knowledge) model 1的 NC 迴歸係數

-   H1b: 迴歸分析無法支持高NC者更新疫情資訊的頻率高於低NC者 model 0: Q12 responses \~ 1 mode1 1: Q12 responses \~ NC\*NCC

model 1的 NC 迴歸係數

-   H1c: 集群分析無法支持高NC者依賴新媒體及可靠管道獲取最新疫情資訊來源的程度高於低NC者

集群分析綜合Q1, Q10, Q10_1\~4, Q12, Q14, Q16, Q17

-   H2: 描述統計顯示高NCC者比低NCC者認為是真實的資訊更有信心( <https://osf.io/8jfwe/> Table 9,10 回答"I am sure this is true"/"I am sure this is not true"的分組信賴區間)；迴歸分析顯示高NCC者對真假資訊及流言說法，都有較高的信心。

(Q1 Knowledge, Conspiracy Rejection分別分析) model 1的NCC迴歸係數

-   H3: 迴歸分析無法支持低認知動機者(低NC,低NCC)容易接受流言說法

(只分析Q1 Conspiracy Rejection) model 1 的 NC\*NCC迴歸係數

3.  描述統計

### 參考文獻
