---
title: "計畫書"
author: "(待補上)"
date: "`r Sys.Date()`"
bibliography: "1_literature/ref.bib"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 緒論

> 明翰：回顧認知動機的定義、問卷開發概念

本研究重製 @bootGatheringProcessingInterpreting2021 的問卷調查及假設分析，探討台灣地區民眾相信正確及錯誤疫情資訊的認知動機因素。

認知動機是什麼？
Need for cognition(認知需求) (原研究的參考資料以及原研究名詞定義內容)

訊息是否具有說服力，則取決於個人內在的動機（Levin & Gaeth, 1988）

定義
當個體在接觸情境下的反應時，其內在動機為思考接收訊息的思考歷程。

解釋:
認知需求的人會接收並辨別資訊的正確性，而非完全注重目前所接收的資訊是否正確。當事人在接收訊息時，對於訊息的內容以及思考的過程感到愉悅。並且較傾向於思考資訊內容的過程。同時也對於較有說服力以及可信的社交平台資訊給予肯定，但也較不會拒絕接受其他可信度不高的社交平台資訊。
我認為認知需求的人在接受資訊時，是享受思考的過程。可能也因為他們善於思考，所以在對資訊本身是否正確有一定的經驗，相較其他非認知需求的人，對於資訊來源以及資訊是否可信的思考方面，認知需求者會更有自信的接收眼前所聽見看見的訊息。

二、認知閉合需求(Need for cognitive closure ) Kruglanski 1997  (freezing & )

定義
當個體在接觸情境下的反應時，其內在動機為思考接收訊息所帶來的結果。

解釋:
認知閉合需求的人在接受知識的思考歷程時，較重於知識本身所帶來的結果。他們傾向接受資訊透露的訊息結果，將其進行固化或凍結。對於認知閉合需求的人來說，他們傾向接收訊息的本身是為了要解決問題，或是因為遇到問題，才會去尋找資訊進而去解決，原研究Boot(2021)也有提到認知閉合者思考時傾向解決事情，或者獲得資訊解決問題來解除自身對於問題所帶來的不安感。

我認為也許對於認知閉合者來說，可能在過去接收資訊時，因個人與情境接觸，產生因接收訊息的方式或訊息內容所帶來的不適感，造成學習時的負向經驗，進而可能如同學習行為論裡的負增強學習理論，接收資訊之後，個體因過往接受訊息後個體感到不舒服，而進而增強下一次不會想主動接收訊息。

問卷來源文獻: @cacioppoNeedCognition1982;  @cacioppoEfficientAssessmentNeed1984

@bootGatheringProcessingInterpreting2021 使用 @cacioppoEfficientAssessmentNeed1984 18題版本


認知動機是什麼?
Need for cognitive closure(認知停歇需求)
訊息是否具有說服力，則取決於個人內在的動機（Levin & Gaeth, 1988）

定義
當個體在接觸情境下的反應時，其內在動機為思考接收訊息所帶來的結果。

解釋:
認知閉合需求的人在接受知識的思考歷程時，較重於知識本身所帶來的結果。他們傾向接受資訊透露的訊息結果，將其進行固化或凍結。對於認知閉合需求的人來說，他們傾向接收訊息的本身是為了要解決問題，或是因為遇到問題，才會去尋找資訊進而去解決，原研究Boot(2021)也有提到認知閉合者思考時傾向解決事情，或者獲得資訊解決問題來解除自身對於問題所帶來的不安感。

我認為也許對於認知閉合者來說，可能在過去接收資訊時，因個人與情境接觸，產生因接收訊息的方式或訊息內容所帶來的不適感，造成學習時的負向經驗，進而可能如同學習行為論裡的負增強學習理論，接收資訊之後，個體因過往接受訊息後個體感到不舒服，而進而增強下一次不會想主動接收訊息。

問卷來源文獻: @kruglanskiPsychologicalTheoryTesting1997

@bootGatheringProcessingInterpreting2021 使用 @kruglanskiPsychologicalTheoryTesting1997 47題版本

參考來源:

@CacioppoNeedforCognitionScale(1984)
@PettyTheneedforcognitioninHandbookofindividualdifferencesinsocialbehavior(2013)
@KruglanskiIndividualdifferencesinneedforcognitiveclosure(1994)
@CacioppoEffectsofneedforcognitiononmessageevaluationrecallandpersuasion(1983)
@KruglanskiMotivatedclosingofthemind‘seizing’ and ‘freezing’(1996)
@KruglanskiNeedforClosureScale(2013) 

> 明翰：台灣學術圈使用NC或NCC問卷，探討資訊解讀或認知態度的研究主題

(2) 國內相關 資訊解讀 或 認知研究 的主題

至千禧之後，國內對於認知需求主題的研究較趨向於兩種主題，其中最多篇幅是廣告與認知需求的相關研究。在搜尋認知需求時，可見不論有沒有使用Cacioppo(1982)認知需求量表，又或是高泉豐(1994)，使用國內修訂Cacioppo認知需求量表中譯版。都可以清楚可見，研究傾向於問卷調查的方式。以某一篇廣告主題為例，研究結果發現，在觀看廣告時，認知需求的類型以及程度，會與參與者本身觀看廣告時的內在動機有關。而不同認知需求的人獲得資訊時的反應會與內在動機有關(方菁容,衛萬里,2013)。另外，回顧國內疫情期間的研究，雖然尚未找到使用認知需求問卷，且與Boot(2021)探討認知需求與獲取疫情資訊及管道的本研究研究主題之相關研究。但許多研究傾向於疫情期間關於學生學習方面為國內關切議題，有如疫情期間大學生留學意願，以及遠距離教學、疫情期間認知與情緒方面的研究等等，可以顯示目前專題討論的文獻回顧有其意義性，也透過疫情等國際事件來看待，我國民眾對於重大事件之獲取資訊時的方法以及思想動機，皆有助於民眾被動或主動意識新冠疫情。


參考來源: 
不同認知需求層級與雙關修辭品質對於平面廣告記憶的影響(楊朝明, 周郁軒,2013)
世界自然基金會(WWF) 環保公益廣告創意效果與觀者認知差異(方菁容,衛萬里,2013)
渴望延遲閉合需求對創意廣告效果之影響(方菁容,衛萬里,鄧成連,2015)
新型冠狀肺炎疫情的認知與情緒(	劉嘉峻,郭妍彤,張鈞豪,孫豪佑,鍾宜蓁,2020)
新冠疫情對大學生留學意願影響之研究-以中部某國立大學為例(蔡䎐宏,2021)

> 采妤：疫情爆發後，全球使用NC或NCC問卷，探討民眾應對疫情資訊及措施的態度或動機研究





> 祥偉、子渝：從目前學術機構或民調中心的資訊，整理台灣社會疫情資訊的樣態; 民眾對疫情資訊的信任度調查

|Boot et al.(2021)原始假設 | 結果支持狀況 |
|---|---|
|H1a: 高NC者對疫情的正確認識高於低NC者 | 充分支持 |
|H1b: 高NC者更新疫情資訊的頻率高於低NC者 | 不支持 |
|H1c: 高NC者依賴新媒體及可靠管道獲取最新疫情資訊來源的程度高於低NC者 | 不支持 |
|H2: 高NCC者比低NCC者對個人認為是真實的資訊更有信心 | 部分支持 |
|H3: 低認知動機者(低NC,高NCC)容易接受流言說法 | 不支持 |



> 與高NCC有關的假設沒有得到充分支持的研究結果可能原因：
> 1. Prolific平台的多數參與者年輕(20y~40y)，會主動吸收最新資訊。
> 2. 研究者採用的流言並非高NCC者能馬上接受的。

## 方法

問卷內容(依原始問卷腳本施測次序):

1. 疫情資訊可信度評估(Q1)：12條真實資訊, 12條不實資訊, 8條流言說法
2. 人口背景調查(Q2 ~ Q7)
3. 媒體使用狀況調查：使用平台(Q8), 每日使用時間(Q9),獲取最新資訊的來源種類(**Q10**) 獲取最新資訊的情境(**Q10_1~4**), 獲取最新資訊的頻率(**Q12**), 獲取最新資訊的動機(**Q14**), 動機調查填充題(Q14_1~5,Q15)
4. 認知動機問卷: NC(Q16),NCC(Q17)

問卷使用網路實驗平台Psytoolkit編制。

### 研究材料

依據原始文獻的研究，研究的材料分別為冠狀病毒之問答題事實題。
1.W1

(1)疫情資訊題目：總共32題，分別為12題真實資訊，12題不實資訊，8題陰謀論，使用李克特5點量表，從"1.我確定這不是真的"到"5.我確定這是真的"。與原始文獻研究材料不同的是，原始研究為2020年，有一些疫情資訊過於老舊，且民眾重視的議題也有所改變，不適用於當今2021年。所以本研究各替換真實資訊與不實資訊各6題，改為疫苗資訊相關的題目，較符合現今社會大眾重視的議題，並更新較舊的疫情資訊。為了避免設計題目沒有證據支持，我們的題目都是由台灣事實查核中心、台灣內科醫學會網路學誌測驗、衛生福利部疾管署、臺大醫院家庭醫學部《COVID-19知識就是力量》參考編制而成，陰謀論則是由台灣適時查核中心與網路新聞平台所參考。題目設定好再交由假新聞清潔劑評估每一題的描述，確認每一題的正確回答4分以上達到80%，以確認訊息呈現的難易度與資訊的正確性，若沒有達成上述條件，則會再做修改或重新找題目。

(2)認知動機「Need for Cognition(NC)」：總共為18題。翻譯自Need for Cognition Scale ，由本研究者由英文翻譯成中文，再請他人由我們翻譯的中文再翻回英文，相互對照，確認翻譯內容與原量表意義相同。

(3)認知停歇需求「Need for Cognition Closure(NCC)」總共為47題。翻譯自Need for Closure Scale (NFC)
 ，由本研究者由英文翻譯成中文，再請他人由我們翻譯的中文再翻回英文，相互對照，確認翻譯內容與原量表意義相同。


### 研究參與者估計 

### 研究程序
1. 確認重制研究題目
2. 編制研究問卷
3. 確認分析計畫
4. 相關文獻探討
5. 收集資料
6. 分析與討論


## 分析計畫

(原研究第一波分析)
1. 疫情資訊回應資料的分類檢測：隨機選取200位參與者的資料進行確證性因素分析，分解兩種因素：Knowledge, Conspiracy Rejection

2. 確設性假設分析

檢測資料符合有Knowledge, Conspiracy Rejection的迴歸式之程度。

(Q1 Knowledge, Conspiracy Rejection分別分析)
model 0: Q1 responses ~ 1
model 1: Q1 responses ~ NC X NCC

- H1a: 迴歸分析確認高NC者掌握資訊的正確度高於低NC者

(只分析Q1 Knowledge)
model 1的 NC 迴歸係數

- H1b: 迴歸分析無法支持高NC者更新疫情資訊的頻率高於低NC者
model 0: Q12 responses ~ 1
mode1 1: Q12 responses ~ NC*NCC

model 1的 NC 迴歸係數

- H1c: 集群分析無法支持高NC者依賴新媒體及可靠管道獲取最新疫情資訊來源的程度高於低NC者

集群分析綜合Q1, Q10, Q10_1~4, Q12, Q14, Q16, Q17

- H2: 描述統計顯示高NCC者比低NCC者認為是真實的資訊更有信心( https://osf.io/8jfwe/  Table 9,10 回答“I am sure this is true"/"I am sure this is not true"的分組信賴區間)；迴歸分析顯示高NCC者對真假資訊及流言說法，都有較高的信心。

(Q1 Knowledge, Conspiracy Rejection分別分析)
model 1的NCC迴歸係數

- H3: 迴歸分析無法支持低認知動機者(低NC,低NCC)容易接受流言說法

(只分析Q1 Conspiracy Rejection)
model 1 的 NC*NCC迴歸係數

3. 描述統計




### 參考文獻

