---
title: 'My note'
author: "張祥偉"
date: "2021/8/12"
bibliography: ref.bib
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Need for cognition
 
研究觀點：陳佳誼與柯書婷(2016)研究中，他們透過認知需求理論探討當高認知需求與低認知需求遇到高複雜的個人化資訊與低複雜的資訊的表現，他們認為高認知需求會比低認知需求還要花費較多心力評估這些資訊，能夠比較回想較多更多訊息，能夠有不同的層面去看，去了解這些個人化的資訊是否對自己有幫助。結果證實，高認知需求的確比低認知需求不管在高低複雜中都能夠花費較多心力分析問題。[@chenjiayiZiXunChengXianMoShiDuiGeRenHuaTuiJianDaiLiRenManYiDuZhiYingXiangRenZhiXuQiuYuJueCeFuZaDuZhiDiaoJieXiaoGuo2016]
研究方法：填答15 題Wolfe and Grosch（1990）所提出的認知需求量表，

個人因素在幽默廣告勸服途徑中之角色研究

研究觀點：練乃華(2002)把認知需求主要分為三種程度高認知需求、中認知需求、低認知需求。使用認知需求主要探討不同程度的認知需求者對於幽默廣告類型表現以及情感密集度他們之間的關聯。研究中主要有三個假設是與認知需求有關。研究結果發現中認知需求者對於認知型幽默、非幽默型廣告表現優於低認知需求者，低認知需求者對於情感性幽默廣告優於兩者，由於中與高認知需求者沒有太大差異所以研究者並沒有做探討。結果證實中認知需求者對於要思考的認知行幽默廣告比較感興趣。[@liannaihuaGeRenYinSuZaiYouMoGuangGaoQuanFuTuJingZhongZhiJiaoSeYanJiu2002]
研究方法：使用(Cacioppo,petty,and Kao) NFC問卷，使用六點量表共18題，研究對象為180名大學生

### H3解釋
|H3: 低認知動機者(低NC,高NCC)容易接受流言說法 | 不支持 |
在原始文獻中研究者認為高NCC比較容易接受陰謀論原因是：大多數高NCC的人為了減少資訊的不確定性更可能傾向支持有關陰謀論言論。但同時他們也認為低NC比較少去主動獲取有關疫情的資訊，所以認為高NCC與低NC比其他組更有機會去接受陰謀論。在最後蒐集完的結果發現NC、NCC與陰謀論拒絕都呈現正相關，並且也證實兩者間並沒有產生交互作用，顯然是不支持原研究者們的假設，研究者列出可能的原因是陰謀論過於誇大，以至於多數人會判斷是虛假訊息，也可能是會接受陰謀論參與者較少，在原始研究中只有14%的參與者在第一波與第二波都支持至少一種陰謀論，顯然樣本偏少，不易測出差異。對於H3的重製，我們盡量限縮陰謀論的訊息，也就是把新聞、報紙常常播報的陰謀論放進去我們的測試題目中，並且把原本關於冠狀病毒8題修改為冠狀病毒陰謀論4題與疫苗資訊陰謀論4題，放在我們的題目中，驗證原研究者假設的出發點或許沒有錯，可能受到參與者對於題目的理解，或是多數參與者的宗教政治立場較開放，使得較少參與者去接收陰謀論於是想放在與原研究不同國家中可能產生不同的結果，為了使我們的陰謀論題目讓參與者更容易接受說法，我們傾向蒐集近期在網路上或各大論壇所談論的資訊，這些資訊都是陰謀論目前並沒有得到證實，而台灣的陰謀論都是對中國大陸所提出的，因台灣比起播報其他國家的陰謀論更喜歡播報中國大陸的陰謀論說法，所以對於如果有在關注這些事件的參與者而言，可能比較容易去接受這些說法。[@WhoEndorsesConspiracy]  

### H1c
H1c: 高NC者依賴傳統媒體及可靠管道獲取最新疫情資訊來源的程度高於低NC者
對於此假設原研究的結果，並不支持此假設，(原因在子渝note)。該假設不支持主要是因為傳統媒體並沒有很頻繁的使用，對於這部分我們也認同，雖然傳統媒體審查嚴謹，符合客觀事實，較少出現假訊息，假新聞等等。但是因現在每人人手一機，相較於傳統媒體，手機網路是或許資訊更快速便利的方式，即使缺少傳統媒體的客觀性與嚴謹性，人們依舊傾向使用新媒體作為獲取資訊的工具，因此該假設雖然較難成立，但能用不同的方式去思考，對於新媒體是否有客觀性不應該一概認為比傳統媒體來的不客觀，在台灣有些新聞網站是比較有公信力，對於客觀性程度可能與報紙相同，所以我認為應該在傳統媒體與新媒體上，不能去比較，如果單就對於可靠管道上，或許是能夠支持假設。[@WhoEndorsesConspiracy]



在重製研究的過程中，我們更改原文獻的研究材料放入疫苗資訊作為新題目，因台灣許多媒體或組織都有做疫苗施打的民調，為了避免有政治干預的媒體對民調有影響，我們盡量挑選符合中立的媒體與非政府組織的民調，在TVBS網站中，訪問時間為2021年5月24日-2021年5月27日。訪問方法為網路問卷SurveyCake平台。回收有效問卷為455104位20歲以上台灣民眾。在問卷設計上，有二個題目方向是關於我們的問卷設計，分別為：1.未來如果開放全民施打新冠肺炎疫苗，請問您會不會去施打新冠肺炎疫苗？有87%(394412人)表示會施打2.詢問參與者若政府購買中國代理商輝瑞BNT疫苗意願施打調查。有80%(361566人)表示會施打。透過這兩個數據我們知道若有疫苗是幾乎都會願意施打，但在中國代理BNT的意願似乎沒有高過於前者。可見對於疫苗的種類上人民依舊會有疑慮。   

###台灣民眾接種國內外疫苗意願調查
資料來源：台灣民意基金會。
為了找尋資料來了解在疫苗選擇不單單只是選擇一種疫苗這麼簡單，往往有許多的考量例如副作用、保護力、剩餘劑量、政治因素等等，這些都會影響著我們對於疫苗的選擇，但在疫苗這麼缺乏的期間，有時候可能不顧是否會有很嚴重的副作用依舊會選擇有疫苗就打的狀況，台灣民意基金會於2021年8月16日到8月18日做了電話調查。有效樣本為1078人年齡為20歲以上。其中在國內外可供選擇疫苗偏好調查中，有一項問題為如果可以自由選擇疫苗情況下AZ、莫德納、BNT、高端會優先選擇哪一種？結果發現有40.9%莫德納、23.8%BNT、11.3%高端、9.5%AZ。而基金會更進一步地問如果能有第二個選擇會選？結果發現33.9%莫德納、24.3%AZ、22.3%BNT、6.7%高端。如果把兩個結果發現結合莫德納的比例是位居第一而高端是位居最後。造成這樣的情況，有幾種可能原因為莫德納的副作用比較少出現死亡個案，而高端有些民眾認為有政治干預，比較不信任，也有可能媒體大肆宣傳高端的陰謀論導致一般民眾對於接種高端就產生許多疑慮。