---
title: "My note"
author: "林子渝"
date: "`r Sys.Date()`"
bibliography: ref.bib
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Need for cognition
廣告的訊息訴求方式、訊息正反性、訊息來源可信度與消費者認知需求對廣告效果之影響。
使用高泉豐(1994)所編的「認知需求的概念與測量」，總共 **12 小題**（前測問卷是 18 小題），採用李克特五點量表。

陳正男等人(2005):"在行銷管理的領域中，不同的認知需求者在觀看廣告時對廣告態度、產品態度、及購買意願皆有所不同，訊息可信度對高低認知需求者都很重要，而低認知需求者較看重正面訊息與感性訴求的訊息；高認知需求者看重反面訊息與理性訴求的訊息。[@AL:10232842-200503-13-1-107-142-a]"
從上述可以看出，訊息的呈現方式可能對不同的認知需求而有差異。而廣告訊息相對於本研究的疫情訊息，或許可以從訊息的正反性看出原始論文H1的假設中，有些高NC大於低NC的假設沒有全部支持的原因，可能就源自於所接觸到的訊息正反性有關。
由此可見在廣告訊息中，呈現出正面訊息對低NC者較有影響，若訊息資訊為正確的，就可能可以使低NC者獲取更多的知識。而若在相同的環境下，多數疫情資訊來源呈現為正面訊息的話，低NC者就有可能跟高NC者記得相等的疫情資訊與知識。



## Boot et al.(2021)原始假設總整理
以下我們將會針對 Boot(2021)研究所提出的假設逐一探討，並評估在我們的重制研究中可能會發生的問題，還有我們如何去解決在原始研究中假設不成立的狀況。

## H1a
原始論文中的假設 H1a：高NC者對疫情的正確認識高於低NC者，結果顯示為「充分支持」，原始研究也發現不只高NC者對疫情資訊的知識與信心顯著高於低NC者，高NCC者也與疫情資訊呈正相關，他們也發現，在疫情資訊題中，對真實資訊呈現的題目表現出更高的準確性，原始論文的給出的解釋為對不實資訊，回答"我不知道"，在理智層面上是屬於誠實回答的部份，因此偏向回答"我不知道"。[@bootGatheringProcessingInterpreting2021]
我們在設計疫情資訊題目時，除了按照原始論文的設計外，我們有對疫情資訊做更新，並加入符合時事的疫苗題，題目部份也進行再三確認，預期也會達到顯著的效果。所謂高NC者，也就是較喜歡思考、較喜歡解決複雜的問題，在解決問題時較會注重過程中的人，反之低NC者則相反。[@bootGatheringProcessingInterpreting2021]所以我們預期高NC者在接收到疫情資訊時，會去思考這些資訊為什麼會導致這結論，也可能去思考、查證疫情資訊的正確性或是來源可靠性，在這其間會比低NC者獲取更多並較正確的疫情資訊，所以高NC者對疫情的正確認識就會高於低NC者。

## H1b
原始論文中的假設 H1b:高NC者更新疫情資訊的頻率高於低NC者，結果顯示為「不支持」。原始論文使用回歸分析發現 NC 與 COVID-19 相關訊息的搜索頻率並無關係，描述性分析表明，大多數人都會主動搜尋 COVID-19 的相關訊息。[@bootGatheringProcessingInterpreting2021]
在我們重製的研究中，由於我們是在台灣地區收集樣本，考慮到自從疫情爆發以來，每天都會有中央流行疫情指揮中心的記者會，因此推測大多數人每天至少會有一次更新疫情資訊的機會，所以可能也無法達到顯注差異，我們推測可能NC高低對危機資訊的更新頻率就較無相關，反而與政府的宣導力度有關。如果政府的宣導力度不會影響或者是不夠強力，我們預期在這項假設達到顯著。

## H1c
原始論文中的假設 H1c: 高NC者依賴傳統媒體及可靠管道獲取最新疫情資訊來源的程度高於低NC者，結果顯示為「不支持」，原研究者假設傳統媒體（報紙、廣播、電視）比社交媒體更有可能經受住嚴密的審查。也有國外的研究顯示，傳統媒體通常會有更客觀的新聞報導，而社交媒體通常包括小報新聞和非官方來源，它們往往有更多聳動的標題與內容，社交媒體用也被證明比真實新聞更快、更廣泛地傳播假新聞。因此原始研究假設，高NC者更可能使用傳統媒體。但結果就跟H1b一樣並不支持，可能是收集到的樣本未能顯著，原始研究並未多做解釋。[@bootGatheringProcessingInterpreting2021]
我認為社交媒體確實有上述的隱憂，傳遞假資訊的速度可能更快、更廣泛，但我覺得這要回歸回始用者如何組成他的社交媒體圈，有些社交媒體帳號也會分享正確且客觀的資訊，況且現今獲取新媒體的方便性遠高於傳統媒體。
該假設不支持主要是因為傳統媒體並沒有很頻繁的使用，對於這部分我們也認同，雖然傳統媒體審查嚴謹，符合客觀事實，較少出現假訊息，假新聞等等。但是因現在每人人手一機，相較於傳統媒體，手機網路是或許資訊更快速便利的方式，即使缺少傳統媒體的客觀性與嚴謹性，人們依舊傾向使用新媒體作為獲取資訊的工具，因此該假設雖然較難成立，但能用不同的方式去思考，對於新媒體是否有客觀性不應該一概認為比傳統媒體來的不客觀，在台灣有些新聞網站是比較有公信力，對於客觀性程度可能與報紙相同，所以我們認為傳統媒體與新媒體不太能去比較，如果單就分析可靠管道上，或許能夠支持此項假設。

## H2
原始論文的假設 H2: 高NCC者比低NCC者對個人認為是真實的資訊更有信心，結果顯示為「部分支持」，確實高NCC者比低NCC者更傾向於回答"我確定這是真的"，但原始研究的研究者們進行推論分析，覺得無法斷定這種影響是由判斷信心、判斷準確度或兩者皆有所引起的，他們也表示未來的研究設計應該要想辦法分離這兩種概念。[@bootGatheringProcessingInterpreting2021]
高NCC者，在面對到外界資訊的刺激時，會傾向確信第一個遇到的答案，並相信這資訊不去變動，會喜歡簡化理解到的第一手資訊，在思考的過呈中看重結果，而較不著重思考歷程。[@AL:U0001-1907201017124300]由上述可知，因為高NCC者會有急迫性與持久性，所以在遇到資訊時會比低NCC者更有信心。我們也預期我們的假設會達到同樣的效果，而在原始研究的建議部分，我們的研究設計並未做太大的更動，我們更新了疫情資訊，也確認了疫情資訊題目並無問題，所以我們期望藉由時事題目，可以降低高NCC者在回答時受判斷準確度的比率。

## H3
原始論文的假設 H3: 低認知動機者(低NC,高NCC)容易接受流言說法，結果顯示為「不支持」，在原始文獻中研究者認為高NCC比較容易接受流言說法原因是：大多數高NCC的人為了減少資訊的不確定性更可能傾向支持有關流言說法的言論。但同時他們也認為低NC比較少去主動獲取有關疫情的資訊，所以認為高NCC與低NC比其他組更有機會去接受流言說法。在最後蒐集完的結果發現NC、NCC與流言說法拒絕都呈現正相關，並且也證實兩者間並沒有產生交互作用，顯然是不支持原研究者們的假設，研究者列出可能的原因是流言說法過於誇大，以至於多數人會判斷是虛假訊息，也可能是會接受流言說法的參與者較少，在原始研究中只有14%的參與者在第一波與第二波都支持至少一種陰謀論，樣本偏少，不易測出差異。[@bootGatheringProcessingInterpreting2021]
原研究的假設可能受到參與者對題目理解的不同，或是多數參與者的宗教政治立場較開放，使得較少參與者去接收流言說法。對於H3的重製我們把原本關於冠狀病毒的流言說法8題修改為冠狀病毒4題與疫苗資訊4題，為了更容易使我們的流言說法題目讓低認知動機的參與者接受，我們傾向蒐集近期在網路上或各大論壇所談論的資訊，這些資訊都是目前並沒有得到證實，而流言說法都是針對中國大陸所提出的，因台灣比起播報其他國家的流言說法更喜歡播報有關中國大陸的流言說法，所以對於如果有在關注這些事件的參與者而言，可能比較容易去接受這些說法。

## 2020年原始研究中的疫情資訊主題
在原始研究中，2020年3月11日世界衛生組織宣布COVID-19全球大流行，當時的許多國家開始實行社交安全距離防疫，疫情資訊主題都圍繞在公共當局對COVID-19爆發而採取的政策和行動，而其中也不乏許多錯誤資訊，


### 研究材料

依據原始文獻的研究，研究的材料分別為冠狀病毒之問答題事實題。
1.W1

(1)疫情資訊題目：總共32題，分別為12題真實資訊，12題不實資訊，8題陰謀論，使用李克特5點量表，從"1.我確定這不是真的"到"5.我確定這是真的"。與原始文獻研究材料不同的是，原始研究為2020年，有一些疫情資訊過於老舊，且民眾重視的議題也有所改變，不適用於當今2021年。所以本研究各替換真實資訊與不實資訊各6題，改為疫苗資訊相關的題目，較符合現今社會大眾重視的議題，並更新較舊的疫情資訊。為了避免設計題目沒有證據支持，我們的題目都是由台灣事實查核中心、台灣內科醫學會網路學誌測驗、衛生福利部疾管署、臺大醫院家庭醫學部《COVID-19知識就是力量》參考編制而成，陰謀論則是由台灣適時查核中心與網路新聞平台所參考。題目設定好再交由假新聞清潔劑評估每一題的描述，確認每一題的正確回答4分以上達到80%，以確認訊息呈現的難易度與資訊的正確性，若沒有達成上述條件，則會再做修改或重新找題目。

(2)認知需求「Need for Cognition(NC)」：
總共為18題。引用自高泉豐修定的修訂的中文認知需求量表。[@gaoquanfengRenZhiXuQiuDeGaiNianYuCeLiang1994]

(3)認知停歇需求「Need for Cognition Closure(NCC)」：
總共為47題。引用自黃瓊億論文中使用的翻譯版本[@U0001-1907201017124300]，由於該版本移除了5題測謊題，在決斷力這因素上的題目也與原始研究不同，為使問卷計分無誤，上述題目由本研究者親自翻譯，再請他人由我們翻譯的中文再翻回英文，相互對照，確認翻譯內容與原量表意義相同。


