---
title: Boot (2021) Gather 文獻引用 
author: "謝明翰"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### 比對標記： ----上:原版 下:修改
```

本研究重製 @bootGatheringProcessingInterpreting2021 的問卷調查及假設分析，探討台灣地區民眾相信正確及錯誤疫情資訊的認知動機因素。
問卷來源文獻: @cacioppoNeedCognition1982; 
@cacioppoEfficientAssessmentNeed1984  


引言:
2020年春天全球爆發的新型冠狀肺炎疫情，不僅考驗世界各國的醫療資源負荷，也挑戰各國公衛措施因應新型傳染病蔓延的能力。公衛措施能發揮效用的重要條件是大眾對疫情狀況的正確認知，例如日常生活落實非藥物介入措施、接種疫苗的必要性等。一般人主動接收與個人生活密切相關最新資訊，以及評估資訊正確性等行動，一直是研究認知動機(cognitive motivation)的心理學者有興趣探討的課題。在此特殊的疫情時期，提供心理學者藉此機會探討傾向相信不真實資訊的一般民眾，個人的認知動機因素。本研究採取重製 @bootGatheringProcessingInterpreting2021 的研究方法，探討台灣民眾相信不實資訊及流言說法的程度，與認知需求(Need for Cognition)與認知閉合需求(Need for Cognitive Closure)等動機因素的關聯性。

------->   2761337..2d2e396  HEAD -> main
### 能理性剖析疫情資訊的認知動機因素 (上面是老師您的)



=======
[(這段放在回顧國內文獻之前)目前台灣著手於認知需求與新冠疫情的研究，仍然還正在萌芽，是個未開發的新領域。目前與認知需求有相關的主題，國內偏向以行銷與廣告為主要篇幅。]
>>>>>>> 31e9ca0d94b973c90846590e7e4ba4d4825e8f15

在疫情爆發[之後]，[台灣的]新聞媒體曾報導「新冠疫情是人造病毒」，或是「新冠疫情是國家戰爭的武器」，等等[未經查核的訊息(citations?)]。[(改寫為簡述Boot等人的研究發現，以及這樣的研究架構用在台灣的情境，預期有什麼不同結果?)有基於此，本研究在重製過程考量到當今2021年台灣各大媒體社交網絡平台(例如:民調基金會，台灣事實查核中心)等民間機構所彙整的疫情資訊，並納入調查問卷製作的題目中，進而理解國內民眾對於陰謀論的看法以及疫情資訊的判別。問卷製作採用原研究者的架構，其中包含陰謀論以及正確陳述與不正確陳述的疫情資訊項目，問卷製作的題目上考量符合國內疫情資訊的實際狀況，因此問卷題目有稍作改良，探討對象是國內20歲以上之大學生及成人的參與者，希望藉由收集到的研究結果，有利於推估國內民眾判斷資訊的情況，了解民眾對疫情的認識。]

[(這段移到研究方法)認知需求，是本研究探討的研究變項，認知需求以及認知閉合需求的問卷，國內外所使用的認知需量表有些不同。國內傾向使用高泉豐(1994)，這份問卷測量是將Cacioppo(1984)認知需求量表，進行中文化的中譯版，從許多國內研究被使用。認知閉合需求則是採用Kruglanski(1997)版本的問卷。最後經由相關人士幫忙校閱問卷題目的設計也附上中英文兩個版本。]





!! --->重製原始論文的假設確立與探討(考量林子渝成員的筆記)

研究假設:
原始論文中的假設 H1a：「高NC者對疫情的正確認識高於低NC者」，結果顯示為「充分支持」，原始研究也發現不只高NC者對疫情資訊的知識與信心顯著高於低NC者，高NCC者也與疫情資訊呈正相關，對於高NCC的人，Kruglanski(1996)認為，高NCC的人思考主要是為了解決問題，或是可以降低他們因問題帶來的不確定，減少不安定的感受。因此高NCC的人他們找到問題的方向以及正確性也很高，且他們相較於低NCC者更有自信相信自己的答案。因此我們從這個假設以及比對原始研究也能看見，高NC以及高NCC者他們更有自信認為接收到的訊息為正確知識。

原始論文中的假設:H1b:「高NC者更新疫情資訊的頻率高於低NC者」，結果顯示為「不支持」。原始論文使用回歸分析發現 NC 與 COVID-19 相關訊息的搜索頻率並無關係，描述性分析表明，大多數人都會主動搜尋 COVID-19 的相關訊息。[@bootGatheringProcessingInterpreting2021]
在我們重製的研究中，由於我們是在台灣地區收集樣本，考慮到自從疫情爆發以來，每天都會有中央流行疫情指揮中心的記者會傳統媒體通常會有更客觀的新聞報導，而社交媒體通常包括小報新聞和非官方來源，它們往往有更多聳動的標題與內容，社交媒體用也被證明比真實新聞更快、更廣泛地傳播假新聞。因此原始研究假設，高NC者更可能使用傳統媒體。但結果就跟H1b一樣並不支持，可能是收集到的樣本未能顯著，原始研究並未多做解釋。[@bootGatheringProcessingInterpreting2021]，因此推測大多數人每天至少會有一次更新疫情資訊的機會，所以可能也無法達到顯注差異，我們推測可能NC高低對危機資訊的更新頻率就較無相關，反而與政府的宣導力度有關，因此此假設就不太符合國內的狀況。如果政府的宣導力度不會影響或者是不夠強力，我們預期在這項假設達到顯著。
傳統媒體通常會有更客觀的新聞報導，而社交媒體通常包括小報新聞和非官方來源，它們往往有更多聳動的標題與內容，社交媒體用也被證明比真實新聞更快、更廣泛地傳播假新聞。因此原始研究假設，高NC者更可能使用傳統媒體。但結果就跟H1b一樣並不支持，可能是收集到的樣本未能顯著，原始研究並未多做解釋


原始論文中的假設 H1c: 「高NC者依賴傳統媒體及可靠管道獲取最新疫情資訊來源的程度高於低NC者」，結果顯示為「不支持」，原研究者假設傳統媒體（報紙、廣播、電視）是給大眾的傳媒，相較其他社交媒體，應該更禁得住嚴密的審查，因此資料較更為客觀也普遍。
(也有國外的研究顯示)，傳統媒體通常會有更客觀的新聞報導，而社交媒體通常包括小報新聞和非官方來源，它們往往有更多聳動的標題與內容，社交媒體用也被證明比真實新聞更快、更廣泛地傳播假新聞。因此原始研究假設，高NC者更可能使用傳統媒體。但結果就跟H1b一樣並不支持，可能是收集到的樣本未能顯著，原始研究並未多做解釋。
。[@bootGatheringProcessingInterpreting2021]
我認為社交媒體確實有上述的隱憂，傳遞假資訊的速度可能更快、更廣泛，但我覺得這要回歸回始用者如何組成他的社交媒體圈，有些社交媒體帳號也會分享正確且客觀的資訊，況且現今獲取新媒體的方便性遠高於傳統媒體。
該假設不支持主要是因為傳統媒體並沒有很頻繁的使用，對於這部分我們也認同，雖然傳統媒體審查嚴謹，符合客觀事實，較少出現假訊息，假新聞等等。但是因現在每人人手一機，相較於傳統媒體，手機網路是或許資訊更快速便利的方式，即使缺少傳統媒體的客觀性與嚴謹性，人們依舊傾向使用新媒體作為獲取資訊的工具，因此該假設雖然較難成立，但能用不同的方式去思考，對於新媒體是否有客觀性不應該一概認為比傳統媒體來的不客觀，在台灣有些新聞網站是比較有公信力，對於客觀性程度可能與報紙相同，所以我們認為傳統媒體與新媒體不太能去比較，如果單就分析可靠管道上，或許能夠支持此項假設。


?1 國外哪篇的研究顯示

=======
>>>>>>> a6a2fba691bb54a8e41d71d43188847b2c6235a8

引言:
2020年春天全球爆發的新型冠狀肺炎疫情，不僅考驗世界各國的醫療資源負荷，也挑戰各國公衛措施因應新型傳染病蔓延的能力。公衛措施能發揮效用的重要條件是大眾對疫情狀況的正確認知，例如日常生活落實非藥物介入措施、接種疫苗的必要性等。一般人主動接收與個人生活密切相關最新資訊，以及評估資訊正確性等行動，一直是研究認知動機(cognitive motivation)的心理學者有興趣探討的課題。在此特殊的疫情時期，提供心理學者藉此機會探討傾向相信不真實資訊的一般民眾，個人的認知動機因素。本研究採取重製 @bootGatheringProcessingInterpreting2021 的研究方法，探討有意願相信不實資訊或流言說法的台灣民眾，認知需求(Need for Cognition)與認知閉合需求(Need for Cognitive Closure)等動機因素，與傾向不相信不實說法的民眾之差異。

我們在文獻回顧過程發現，目前台灣著手於認知需求與新冠疫情的研究，仍然還正在萌芽，是個未開發的新領域。目前與認知需求有相關的主題，國內偏向以行銷與廣告為主要篇幅。在疫情爆發的同時，國內新聞媒體曾報導「新冠疫情是人造病毒」，「或是新冠疫情是國家戰爭的武器」，等等的一些假設。有基於此，本研究在重製過程考量到當今2021年台灣各大媒體社交網絡平台(例如:民調基金會，台灣事實查核中心)等民間機構所彙整的疫情資訊，並納入調查問卷製作的題目中，進而理解國內民眾對於陰謀論的看法以及疫情資訊的判別。問卷製作採用原研究者的架構，其中包含陰謀論以及正確陳述與不正確陳述的疫情資訊項目，問卷製作的題目上考量符合國內疫情資訊的實際狀況，因此問卷題目有稍作改良，探討對象是國內20歲以上之大學生及成人的參與者，希望藉由收集到的研究結果，有利於推估國內民眾判斷資訊的情況，了解民眾對疫情的認識。認知需求，是本研究探討的研究變項，認知需求以及認知閉合需求的問卷，國內外所使用的認知需量表有些不同。國內傾向使用高泉豐(1994)，這份問卷測量是將Cacioppo(1984)認知需求量表，進行中文化的中譯版，從許多國內研究被使用。認知閉合需求則是採用Kruglanski(1997)版本的問卷。最後經由相關人士幫忙校閱問卷題目的設計也附上中英文兩個版本。




## 認知動機是什麼?

1. 認知需求(Need for cognition)
認知動機為原本為Wolfe(1955)等人創造，當事者內在動機為接收知識的歷程。
認知需求的人喜歡思考的歷程，他們普遍想要了解知識。因此這些人可能會運用不同的管道去獲得知識，並從中判斷資訊的真實度。自從Cacioppo以後，便開始也有很多學者定義認知需求，例如Durvasula, and Akhter（1990）將個人的認知需求定義為，處理廣告訊息的動機（Zhang and Buda, 1999），國內也有學者對認知需求定義，「表示個人對「建構關鍵情境為有意義與統整的形式」的需求高低，也就是將特定情境轉化為個人系統的需求，此需求強度是因人而異（周惠珍，1999）。

----上:原版 下:修改

認知需求動機最早為Wolf(1955)等人提出的概念，探討個人需要理解知識的內在動機歷程。Cacioppo(?)認為高認知需求的人喜歡思考的歷程，想要儘可能理解能解答眼前問題的各種資訊，合理推測認知需求越高的人越會採取行動從不同的管道獲取資訊，並且會認真判斷資訊的真實度。認知需求的概念進一步在需要理解特定資訊的情境中，發展為各式研究主題，像是能提高認知需求的廣告訊息設計(Zhang and Buda, 1999)。[周惠珍(1999)的研究主題？]

[說明 @cacioppoEfficientAssessmentNeed1984 設計的問卷項目如何建構認知需求動機的量測]

2. 認知閉合需求(Need for Cognitive closure)



## 國內使用認知需求問卷的研究狀況:

1. 首先先說明使用了什麼研究



國內使用認知需求問卷的研究狀況:

過去的研究發現國內對於認知需求的研究有許多篇幅偏向行銷與廣告。而在國內認知需求問卷使用，有經由文獻回顧發現國內認知需求量表中譯版高泉豐(1994)，並透過瀏覽後證實此份針對問卷改良的文獻是Cacioppo(1984)的中譯版本，也在不少國內認知需求主題的相關研究被使用。另外在本重製研究透過文獻回顧找出國內外研究也有使用Cacioppo(1984)、高泉豐(1994)。

(高泉豐做了什麼，可能要再回去回顧)


認知需求相關主題的文獻:

國內對於認知需求主題相關的文獻涉及消費者以及廣告方面，廣告的介入(曾忠蕙， 王又鵬，民國95年)，將行銷手法中小額建構方式以及總額建構方式的行銷手法呈現於商品中。對於消費者而言「小額建構方式下所貶值的損失金額比較小」，研究結果發現小額建構方式更使消費者買單，研究將認知需求當作中介考量。發現消費者的認知需求程度會影響購買行為。雖然並未與資訊解讀主題相關，因此比較沒有與原研究Boot(2021)上的假設有什麼關聯探討。也許認知需求與資訊解讀的研究，目前在國內還沒有發展，可能會是未來探討認知需求研究的其中一種方向。

認知動機與資訊解讀相關研究，Kaynar(2007)的研究結果發現高認知需求者使用互聯網的信息服務高於低認知需求者。與Boot(2021)同樣都有將認知需求(need for cognition)用於研究。Kaynar(2007)可以知道研究者在意的是認知需求者使用網站的意圖，而Boot(2021)，則是透過疫情爆發後，社會媒體使用的頻率，所以兩者討論的對象相同，不過所要看見的依變項結果，有不一樣的層面。




國外認知動機與資訊解讀相關研究:

對於認知Kaynar(2007)研究探討認知需求程度與互聯網信息使用，研究結果發現高認知需求者的使用互聯網信息服務高於於低認知需求者。且高認知需求者透過皮爾森相關分系，得知更傾向於專業服務的信息。與同樣考量認知需求的原研究Boot(2021)，在研究結果的方向上有很大的不同，Kaynar(2007)，研究結果在意的是使用互聯網的動機，而Boot(2021)則探討認知需求程度與使用媒體資訊的管道以及頻率。兩個研究雖然沒有直接關連性，但可知，都將認知需求以及社交媒體運用於研究。對於高認知需求者而言，他們思考時注重思考歷程。而專業信息的網站，更能夠讓他們學習以及獲取知識。而Boot(2021)也提及高認知需求者更傾向理解不同的疫情資訊，在媒體使用上，或許兩者同樣都以認知需求角度出發，而因不同假設設定，使得研究結果呈現了可以綜合認知需求與資訊的研究成果。讓我們有一個對認知需求的人有一個初步的概念，他們傾向於理解資訊，以及因為喜歡思考，而在資訊快速的時代，網路變成他們快速獲取知識的媒介，也使得這些人使用資訊媒體的動機有別於其他人。
  
  
  
----上:原版 下:修改

高泉豐(1994)由於有參與最初版本的認知需求問卷開發(Cacioppo等人,1984)，採用相同的構念與研究方法建立中文版常模，也成為台灣學術界研究認知需求的各領域研究者，最常使用的測量工具。例如曾忠蕙， 王又鵬(1996)比較兩種廣告行銷手法的效果，並且評估認知需求做為中介變項如何影響購買行為。網路平台逐漸成為一般人獲取資訊的主要管道之後，國內外學者均有探討認知需求如何調節所關心的目標行為。例如[(陳佳誼 & 柯書婷, 2016) ... ]。Kaynar(2007)發現高認知需求者比低認知需求者更容易接受網路服務，並且更傾向透過網路取得專業資訊與服務。





**國外認知需求與媒體使用相關研究:


(1) OK
=======


---------
國內疫情以前，有沒有人用認知動機的概念來去解決一些台灣的事情。

**國外認知需求與媒體使用相關研究:  (再來花點時間討論國外，先弄國內。)
國外先不要花時間，但可以學習閱覽。

疫情前，認知動機以及認知閉合需求，有沒有國內研究拿來做。  ( (1)解決重大問題，(2) 人們為何容易相信陰謀論。)


(1) OK
<<<<<<< HEAD
=======
國外認知需求與媒體使用相關研究:
(1)

國外的部分仍然有探究互聯網使用與認知需求Kaynar a, Yair Amichai-Hamburger(2008)，雖然並非與Boot(2021)使用相同的問卷，但是透過因素分析結果發現，高認知需求的者相對於低認知需求者更傾向用更多時間使用網路，且研究還發現，在皮爾森相關分析中，高認知需求者使用網路的目的偏向於互聯網提供之專業信息服務。


(2)
這是一個中國在線調查，屬於網路研究，Yan Su(2021)等人進行一項來自中國的在線調查 (N = 731)，並研究了中國和國際社交媒體使用對 COVID-19 陰謀論認可 (CTE)的條件性間接影響。其中裡面有提及認知需求程度的不同可能也是一個間接影響陰謀論認可的原因。
 假設共有四個以及三個研究問題。其中研究假設四則提到，參與者認知需求的程度是否會影響陰謀論的支持。
 並無使用與Boot(2021)相關的問卷
 
(3) 
NC(認知需求)與主流新聞曝光的探討，研究目的是想知道以認知需求為中介變項的介入，和主流媒體懷疑與主流曝光的關係。Yariv Tsfati(2005)et.al等學者在這份研究提及三個假設。
研究假設:
假設1: 主流媒體懷疑與主流媒體曝光降低互有關係。
假設2: 認知需求將與主流媒體曝光有正相關。
假設3: 新聞媒體的懷疑在影響主流新聞媒體曝光時會與NC互動。  NC水平高的媒體懷疑的影響會減弱，NC水平低的媒體懷疑的影響會更強


增加H1c假設: 原研究將參與者分為四組，其中一組為低NC，且低NCC的人，研究假設這類的人更傾向於接受陰謀論，則內文中也提及，認知閉合者傾向將接收的知識凍結Kruglanski()，而實際上對於高認知閉合需求者而言，在新中確定了資訊後，凍結資訊前，藉由傳播媒體不斷的接收、聆聽，透過電視影音等媒介觀看相似的訊息，則更有可能讓高認知閉合需求者認為他們所接收的訊息就是知識。因此我們在H1c的假設做適當的修改，對於認知需求低的人，接收訊息的管道可能涉及傳統媒體以及網路社交平台。自從疫情之後，訊息不斷地在各平台以不同的詮釋出現，可能更容易促進低認知需求者在理解疫情資訊時被動接受陰謀論的說法。基於上述，我們假設低認知需求且高認知閉合需求者的這一組參與者將更容易相信陰謀論。




