---
title: Boot (2021) Gather 文獻引用 
author: "謝明翰"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### 比對標記： ----上:原版 下:修改
```

本研究重製 @bootGatheringProcessingInterpreting2021 的問卷調查及假設分析，探討台灣地區民眾相信正確及錯誤疫情資訊的認知動機因素。
問卷來源文獻: @cacioppoNeedCognition1982; 
@cacioppoEfficientAssessmentNeed1984  


引言:
2020年春天全球爆發的新型冠狀肺炎疫情，不僅考驗世界各國的醫療資源負荷，也挑戰各國公衛措施因應新型傳染病蔓延的能力。公衛措施能發揮效用的重要條件是大眾對疫情狀況的正確認知，例如日常生活落實非藥物介入措施、接種疫苗的必要性等。一般人主動接收與個人生活密切相關最新資訊，以及評估資訊正確性等行動，一直是研究認知動機(cognitive motivation)的心理學者有興趣探討的課題。在此特殊的疫情時期，提供心理學者藉此機會探討傾向相信不真實資訊的一般民眾，個人的認知動機因素。本研究採取重製 @bootGatheringProcessingInterpreting2021 的研究方法，探討台灣民眾相信不實資訊及流言說法的程度，與認知需求(Need for Cognition)與認知閉合需求(Need for Cognitive Closure)等動機因素的關聯性。

### 能理性剖析疫情資訊的認知動機因素 (上面是老師您的)

[(這段放在回顧國內文獻之前)目前台灣著手於認知需求與新冠疫情的研究，仍然還正在萌芽，是個未開發的新領域。目前與認知需求有相關的主題，國內偏向以行銷與廣告為主要篇幅。]

疫情爆發之後，有一群學者關注認知方面的研究，Boot(2020)等人藉由疫情，探討人們認知需求程度與資訊解讀。研究透過正確疫情資訊以及錯誤疫情資訊各12題，以及陰謀論8題，兩個面向探討人們對疫情資訊的了解情況。研究發現在在H1a的研究假設裡，高認知需其者對於疫情的正確知識，高於低認知需求者。其餘的部分對於疫情更新的頻率以及依賴新媒體獲取管道等其他假設，研究假設相較假設H1a來說並不充分。我們藉由重製Boot(2020)的研究，想了解國內不同認知需求的人對於疫情資訊，使用哪些媒體管道，與認知動機需求的的狀況。在瀏覽國內認知方面的研究之後，目前國內尚未有其他研究團隊探討認知需求與疫情資訊解讀的研究。因此使得本研究的執行。在重製過程考量到國內網站資訊蒐集的問題，於是研究參考台灣各大媒體社交網絡平台(例如:民調基金會，台灣事實查核中心)等民間機構所彙整的疫情資訊，並納入調查問卷製作的題目中，進而理解國內民眾對於陰謀論的看法以及疫情資訊的判別。問卷製作採用原研究者的架構，其中包含陰謀論以及正確陳述與不正確陳述的疫情資訊項目，問卷製作的題目上考量符合國內疫情資訊的實際狀況，因此問卷題目有稍作改良，探討對象是國內20歲以上之大學生及成人的參與者，希望藉由收集到的研究結果，有利於推估國內民眾判斷資訊的情況，了解民眾對疫情的認識。


>>>     1103
引言 

  2020年春天全球爆發的新型冠狀肺炎疫情，不僅考驗世界各國的醫療資源負荷，也挑戰各國公衛措施因應新型傳染病蔓延的能力。公衛措施能發揮效用的重要條件是大眾對疫情狀況的正確認知，例如日常生活落實非藥物介入措施、接種疫苗的必要性等。一般人主動接收與個人生活密切相關最新資訊，以及評估資訊正確性等行動，一直是研究認知動機(cognitive motivation)的心理學者有興趣探討的課題。在此特殊的疫情時期，提供心理學者藉此機會探討傾向相信不真實資訊的一般民眾，個人的認知動機因素。本研究採取重製 @bootGatheringProcessingInterpreting2021 的研究方法，探討台灣民眾相信不實資訊及流言說法的程度，與認知需求(Need for Cognition)與認知閉合需求(Need for Cognitive Closure)等動機因素的關聯性。
  
  疫情爆發之後，各大社交媒體以及傳統媒體播報疫情資訊。在認知方面Boot(2020)等人藉由各大傳媒提供的訊息，想了解當地民眾對於疫情正確與不正確資訊的判別以及民眾相信或能否區別陰謀論。探討認知動機與疫情資訊解讀的研究，進而理解認知動機對於資訊解讀，疫情更新頻率，資訊獲取管道的關係。本次重製研究(以下稱本研究)，也依照原始研究探討國內民眾對於疫情資訊的實際解讀情形。
  
  我們藉由重製Boot(2020)的研究，想了解國內不同認知需求的人對於疫情資訊，使用哪些媒體管道，與認知動機需求的狀況。由於本研究已屬於的工具主要為問卷調查的方式進行，因此問卷製作仍採用原研究者的架構，其中包含陰謀論以及正確陳述與不正確陳述的疫情資訊項目，陰謀論，以及認知需求程度不同的人對疫情的更新頻率等不實資訊相信的程度。問卷製作的題目上考量符合國內疫情資訊的實際狀況，因此問卷題目有稍作改良。研究參與對象包含國內20歲以上之大學生及成人的參與者，希望藉由收集到的研究結果，有利於推估國內民眾判斷資訊的情況，了解民眾對疫情的認識。
  
  

 <!---2020年疫情爆發之後有陸陸續續的研究想要探討與新冠肺炎有關的知識。其中Boot(2020)等人探討疫情期間不同認知需求的人獲得知識以及尋求資訊管道的研究。我們透過重製Boot(2021)的研究，了解是否因為認知需求的差異與國內民眾對於獲得知識以及尋求資訊管道之間的關係。以下我們--->
 
 <!---
疫情爆發至今已經快滿兩年，國外有學著針對認知領域在疫情期間做了相關的研究，Boot(2020)透過對於認知動機類型來了解當地民眾對於疫情正確資訊與不正確資訊的調查。本研究想藉由重製Boot(2020)了解台灣民眾對於掌握正確並區別不正確疫情資訊以及判別陰謀論資訊的狀況。我們在文獻回顧過程發現，目前台灣著手於認知需求與新冠疫情的研究，仍然還正在萌芽，是個未開發的新領域。目前與認知需求有相關的主題，國內偏向以行銷與廣告為主要篇幅。 在疫情爆發的同時，國內新聞媒體曾報導「新冠疫情是人造病毒」，「或是新冠疫情是國家戰爭的武器」，等等的一些假設。有基於此，本研究在重製過程，考量到當今2021年台灣各大媒體社交網絡平台(例如:民調基金會，台灣事實查核中心)等民間機構所彙整的疫情資訊，並納入調查問卷製作的題目中，進而理解國內民眾對於陰謀論的看法以及疫情資訊的判別。問卷製作採用原研究者的架構，其中包含陰謀論以及正確陳述與不正確陳述的疫情資訊項目。 重製調查問卷過程中，問卷製作的題目上有稍作改良，因本研究是探討國內20歲以上之大學生的參與者，基於收集到的研究結果，再去推估國內民眾判斷資訊的情況。認知需求，是本研究探討的研究變項，認知需求以及認知閉合需求的問卷，國內外所使用的認知需量表有些不同。國內傾向使用高泉豐(1994)，這份問卷測量是將Cacioppo(1984)認知需求量表，進行中文化的中譯版，從許多國內研究被使用。認知閉合需求則是採用Kruglanski(1997)版本的問卷。最後經由相關人士幫忙校閱問卷題目的設計也附上中英文兩個版本。

< 標題與內文不對
在文獻回顧的過程中發現，搜尋認知需求的相關文獻時，國內外所使用的認知需量表有差異，我國傾向於使用高泉豐(1994)年對Cacioppo(1984)認知需求量進行中文化的中譯版。另外經由瀏覽過去認知需求的研究以及透過資料蒐集與重製資料過程，也提出與Boot(2021)原研究假設的一些不同看法。研究使用認知需求(Need for cognition)以及認知閉合需求(Need for cognitive closure0)的問卷，均有中英文版本，並透過臉書社群假新聞清潔劑粉絲專業進行審理。---> 



#研究方法 


認知動機的類別，是本研究探討的研究變項，其中分為認知需求以及認知閉合需求。國內外所使用的認知需量表有些不同。國內傾向使用高泉豐(1994)，這份問卷測量是將Cacioppo(1984)認知需求量表，進行中文化的中譯版。認知閉合需求則是採用Kruglanski(1997)版本的問卷。最後經由相關人士幫忙校閱問卷題目的設計也附上中英文兩個版本。
本研究透過問卷調查的方式，使用高泉豐(1994)認知需求量表，此量表為Cacioppo(1984)英文版問卷透過翻譯並校對後的中文譯版。問卷題目則是採用李克特氏五點量表，總共有18題題目，每題陳述句的評分由1到5分，分別為陳述的特徵與我非常不相似(extremely uncharacteristic of me)，陳述的特徵有些地方與我不相似(some uncharacteristic of me)，沒有特徵(uncertain)，以及陳述的特徵有些與我相似(some characteristic of me)，以及陳述的特徵有些與我非常相似(extremely characteristic of me)。認知閉合需求則是採用



# 建議

Boot等人整理的三種疫情資訊，各種認知動機者的信任度有何不同？這是假設與研究結果突顯的重點。

# **重製Boot et al.(2021)原始假設** (整合老師撰寫的研究發現與團隊的假設整理)

對於認知需求及認知閉合需求評分有明顯差異的四組參與者，Boot等人預期對於疫情資訊的接收與判斷有以下假設及發現:

整理Boot等人整理的三種疫情資訊，各種認知動機者的信任度有何不同？這是假設與研究結果突顯的重點。
透過觀察補充資料8~11關於四組(Hi-NC,Hi-NCC).(Hi-NNC,Lo-NCC).(Lo-NC,Hi-NCC).(Lo-NC,Lo-Ncc)在疫情資訊與陰謀論的回答狀況。原始研究將正確資訊的評估，以同一組的人比較。Boot在四組分數比較時，對於正確的疫情資訊，低NC/高NCC受訪者平均評估了64.2%（95%CI[59.9，68.5]）的真實陳述，並帶有"我確信這是真的"相比之下，低NC/高NCC受訪者評估了23.2%（95%CI[19.0，27.4]）的真實陳述，並帶有"我認為這是真的"。

本研究為了要確定各組認知動機對於疫情資訊以及陰謀論的信任程度。在正確資訊，我們將以同一個"我認為這是真的"的回應選項來看待每一組認知動機的差別。高NC/高NCC受訪者平均評估了63.5%（95%CI[58.6，68.5]），在低NC/高NCC受訪者平均評估了64.2%（95%CI[59.9，68.5])，
，在高NC/低NCC受訪者平均評估了53.8%（95%CI[48.7，59.0]），低NC/低NCC受訪者平均評估了47.8%（95%CI[40.5，55.0]）。其中我們可以從補充資料的數據看到，在"我認為是真的"選項，與其他選項
比較來看，高NC/高NCC與低NC/低NCC的差距有10%左右。因此從數據上來看，有助於解釋，高NCC者相較低NCC者更相信自己認為的疫情資訊是真的。而在錯誤疫情資訊方面，用回應"我認為這不是真的"選項，看待每一組認知動機的差別。高NC/高NCC受訪者平均評估了51.0%（95%CI[46.2，55.7]），在低NC/高NCC受訪者平均評估了43.2%（95%CI[38.8，47.5])，在高NC/低NCC受訪者平均評估了47.8%（95%CI[42.8，52.8]），低NC/低NCC受訪者平均評估了34.1%（95%CI[28.1，40.2]），可以從數據上看到，在"我認為這不是真的"選項，與其他選項比較來看，高NC/高NCC與低NC/低NCC的差距有17%左右。可以知道高NC者相較低NC者，與高NCC者相較低NCC者，高NC者與高NCC者更相信自己認為的錯誤資訊不是真的。這似乎可以解釋疫情知識的陳述方面，假設一中的H1a(高NC者對疫情的正確認識高於低NC者)以及假設二(高NCC者比低NCC者對個人認為是真實的資訊更有信心)更有說服力。
=======
在研究假設的發現，原始研究者Boot等人的研究目的在緒論有表明，想了解人們收集、處理、解釋資訊方面，是否與認知動機不同有關聯。因此假設設立的部分有考量到，對於媒體的使用，資訊涉及的管道，以及研究討論對象認知動機的探討。原始研究者假設認知需求的人會傾向主動蒐集資訊，而其中高認知需求者對於疫情的蒐集以及更新頻率將大於低認知需求者。也因此提出由三個情境組成的假設一H1a:高NC者對疫情的正確認識高於低NC者，H1b:高NC者更新疫情資訊的頻率高於低NC者，以及H1C:高NC者依賴新媒體及可靠管道獲取最新疫情資訊來源的程度高於低NC者。在假設二則是探討認知閉合需求者，對於疫情知識(包含正確與錯誤資訊)，所認同的程度做考量。認知閉合需求者的人傾向以解決問題為思考的重心，而對於高認知閉合需求者原始研究者認為，他們會也會主動蒐集資訊，並且更容易認同自己所相信的資訊為真實資訊。有基於此，提出假設二高NCC者比低NCC者對個人認為是真實的資訊更有信心。另外，本研究在重製的過程，同樣也將原始研究者視陰謀論的想法為研究探討的對象之一。根據疫情剛爆發期間，研究者認為人們在很大程度上依賴（數位）媒體來收集資訊並瞭解與COVID-19相關的發展。原始研究者也從事實核查中心，找到中心人員紀錄將近有225條資訊皆是錯誤的資訊。流行病事關重大社會事件，在我們無法有效隔絕陰謀論的情況下，這些的事件也可能在疫情期間被接受。原始研究者也提及大流行病剛爆發期間，人們為了要排除對於事件的不確定所造成的不安感，會傾向於接受陰謀論的說法。而其中研究者從假設二進一步地去思考認知動機中，認知閉合需求的人相較認知需求的人，應更為符合。另外在假設三的部分本研究認為是綜合假設一跟二，原始研究者將認知動機以及程度因此分成了四種狀況，而從中低認知動機者，在這裡分別為低認知需求且高認知閉合需求組(低NC,高NCC)更傾向容易接受陰謀論的流言說法，於是提出假設三。






整理Boot等人整理的三種疫情資訊，各種認知動機者的信任度有何不同？這是假設與研究結果突顯的重點。

1215 

在研究發現與結果的部分，透過觀察補充資料8~11關於四組(Hi-NC,Hi-NCC).(Hi-NNC,Lo-NCC).(Lo-NC,Hi-NCC).(Lo-NC,Lo-Ncc)在疫情資訊與陰謀論的回答狀況。原始研究將正確資訊的評估，以同一組的人比較。對於正確的疫情資訊，低NC/高NCC受訪者平均評估了64.2%（95%CI[59.9，68.5]）的真實陳述，並帶有"我確信這是真的"相比之下，低NC/高NCC受訪者評估了23.2%（95%CI[19.0，27.4]）的真實陳述，並帶有"我認為這是真的"。為了重新看待原始研究的數據考量研究假設以及確定各組認知動機對於疫情資訊以及陰謀論的信任程度。在正確資訊，我們將以同一個"我認為這是真的"的回應選項來看待每一組認知動機的差別。高NC/高NCC受訪者平均評估了63.5%（95%CI[58.6，68.5]），在低NC/高NCC受訪者平均評估了64.2%（95%CI[59.9，68.5])，在高NC/低NCC受訪者平均評估了53.8%（95%CI[48.7，59.0]），低NC/低NCC受訪者平均評估了47.8%（95%CI[40.5，55.0]）。
其中我們可以從補充資料的數據看到，在"我認為是真的"選項，與其他選項比較來看，高NC/高NCC與低NC/低NCC的差距有10%左右。這似乎可以解釋疫情知識的陳述方面，假設一中的H1a(高NC者對疫情的正確認識高於低NC者)。另外，從數據上來看，相較低NCC者而言，高NCC者應更相信自己認為的疫情資訊是真的。結果符合假設二的設定。而在錯誤疫情資訊方面，用回應"我認為這不是真的"選項，看待每一組認知動機的差別。高NC/高NCC受訪者平均評估了51.0%（95%CI[46.2，55.7]），在低NC/高NCC受訪者平均評估了43.2%（95%CI[38.8，47.5])，在高NC/低NCC受訪者平均評估了47.8%（95%CI[42.8，52.8]），低NC/低NCC受訪者平均評估了34.1%（95%CI[28.1，40.2]），可以從數據上看到，在"我認為這不是真的"選項，與其他選項比較來看，高NC/高NCC與低NC/低NCC的差距有17%左右。可以知道高NC者相較低NC者，與高NCC者相較低NCC者，高NC者與高NCC者更相信自己認為的錯誤資訊不是真的。從研究結果看待疫情知識的陳述方面(包含正確與錯誤資訊)，由統計結果我們可以這樣解釋，四組認知動機的每一組，能顯示對於疫情知識回應的信任程度。




假設1:H1a高NC者對疫情的正確認識高於低NC者
      H1b: 高NC者更新疫情資訊的頻率高於低NC
      H1C:高NC者依賴新媒體及可靠管道獲取最新疫情資訊來源的程度高於低NC者
      
(一) 因為高認知需求者更喜歡思考的歷程，他們有興趣的是思考帶來的樂趣，不只是為了解決問題或得到簽案。因此Boot等人假設相對於低認知需求者，高認知需求者對於疫情(a)有較多的正確知識，(b)較常更新疫情資訊，以及(c)更依賴由可查核消息來源的訊息管道獲取最新疫情資訊。研究結果顯示認知需求評分與真實疫情資訊的確信程度有明顯正相關，他們也發現，在疫情資訊題中高認知需求者對真實資訊呈現的題目表現出更高的準確性。但是與流言說法的確信程度有明顯負相關；認知需求評分與參與的搜索疫情訊息頻率無明顯關係，不過描述性分析顯示多數參與者會主動搜尋；集群分析(cluster analysis)無法從認知動機問卷評分、疫情資訊確信度、以及媒體使用狀況調查等調查資訊，區辨高認知需求動機者獲得疫情資訊所偏好的媒體管道。總結研究結果只有支持高認知需求者有較多正確知識。


假設H2:高NCC者比低NCC者對個人認為是真實的資訊更有信心
(二)高NCC者比低NCC者對個人認為是真實的資訊更有信心，結果顯示為「部分支持」，確實高NCC者比低NCC者更傾向於回答"我確定這是真的"。Boot等人預期高認知閉合需求者對於自認為是真實的資訊，不論是否為事實都會有信心。雖然結果顯示高認知閉合需求者對於真實資訊的信心評估明顯高於低認知閉合需求者，兩者對於流言說法的信心評估則無明顯差異。原始研究也進行推論分析，覺得無法斷定這種影響是由判斷信心、判斷準確度或兩者皆有所引起。在原始結果討論，學者也告知未來的研究設計應該要想辦法分離這兩種概念。Boot認為最可能的原因是，認知閉合需求問卷無法區分參與者的信心是根據符合急迫性的資訊，還是形成持久性的資訊。而且在疫情剛爆發時期，資訊變動頻繁，不論參與者的認知閉合需求程度，比較不會認定各種謠言及陰謀說法的真實性。所以他們的研究結果只有支持這項假設的部分預測。



假設H3: 低認知動機者(低NC,高NCC)容易接受流言說法 
(三) 低認知動機者(低NC,高NCC)容易接受流言說法，結果顯示為「不支持」，原始研究者認為陰謀論有助於在疫情剛爆發時降低民眾對大流行病的不確定，為疫情提供了一些說法，使得民眾在不確定性情況下有個判斷能夠先減緩不安感。而大多數高NCC者為了減少資訊的不確定性，更可能傾向支持有關流言說法的言論。同時，他們也認為低NC比較少去主動獲取有關疫情的資訊。
研究結果發現，大部分有將近57.4%的人能夠完全拒絕8題陰謀論，且只有14%的參與者在第一波與第二波都支持至少一種陰謀論，樣本偏少，不易測出差異。由於預期低認知需求且高認知閉合需求者有最低的認知動機，Boot等人預期此組參與者對流言說法的確信和會高於有較高認知動機的參與者，包括高認知需求且高認知閉合需求者、高認知需求且低認知閉合需求、以及低認知需求且低認知閉合需求者。然而Boot等人的迴歸分析顯示認知需求與認知閉合需求的交互作用迴歸係數，無法解釋流言說法的確信度變異。因此這項假設並未得到正面結果支持。





?1 國外哪篇的研究顯示

引言:
2020年春天全球爆發的新型冠狀肺炎疫情，不僅考驗世界各國的醫療資源負荷，也挑戰各國公衛措施因應新型傳染病蔓延的能力。公衛措施能發揮效用的重要條件是大眾對疫情狀況的正確認知，例如日常生活落實非藥物介入措施、接種疫苗的必要性等。一般人主動接收與個人生活密切相關最新資訊，以及評估資訊正確性等行動，一直是研究認知動機(cognitive motivation)的心理學者有興趣探討的課題。在此特殊的疫情時期，提供心理學者藉此機會探討傾向相信不真實資訊的一般民眾，個人的認知動機因素。本研究採取重製 @bootGatheringProcessingInterpreting2021 的研究方法，探討有意願相信不實資訊或流言說法的台灣民眾，認知需求(Need for Cognition)與認知閉合需求(Need for Cognitive Closure)等動機因素，與傾向不相信不實說法的民眾之差異。

我們在文獻回顧過程發現，目前台灣著手於認知需求與新冠疫情的研究，仍然還正在萌芽，是個未開發的新領域。目前與認知需求有相關的主題，國內偏向以行銷與廣告為主要篇幅。在疫情爆發的同時，國內新聞媒體曾報導「新冠疫情是人造病毒」，「或是新冠疫情是國家戰爭的武器」，等等的一些假設。有基於此，本研究在重製過程考量到當今2021年台灣各大媒體社交網絡平台(例如:民調基金會，台灣事實查核中心)等民間機構所彙整的疫情資訊，並納入調查問卷製作的題目中，進而理解國內民眾對於陰謀論的看法以及疫情資訊的判別。問卷製作採用原研究者的架構，其中包含陰謀論以及正確陳述與不正確陳述的疫情資訊項目，問卷製作的題目上考量符合國內疫情資訊的實際狀況，因此問卷題目有稍作改良，探討對象是國內20歲以上之大學生及成人的參與者，希望藉由收集到的研究結果，有利於推估國內民眾判斷資訊的情況，了解民眾對疫情的認識。認知需求，是本研究探討的研究變項，認知需求以及認知閉合需求的問卷，國內外所使用的認知需量表有些不同。國內傾向使用高泉豐(1994)，這份問卷測量是將Cacioppo(1984)認知需求量表，進行中文化的中譯版，從許多國內研究被使用。認知閉合需求則是採用Kruglanski(1997)版本的問卷。最後經由相關人士幫忙校閱問卷題目的設計也附上中英文兩個版本。




## 認知動機是什麼?

1. 認知需求(Need for cognition)
認知動機為原本為Wolfe(1955)等人創造，當事者內在動機為接收知識的歷程。
認知需求的人喜歡思考的歷程，他們普遍想要了解知識。因此這些人可能會運用不同的管道去獲得知識，並從中判斷資訊的真實度。自從Cacioppo以後，便開始也有很多學者定義認知需求，例如Durvasula, and Akhter（1990）將個人的認知需求定義為，處理廣告訊息的動機（Zhang and Buda, 1999），國內也有學者對認知需求定義，「表示個人對「建構關鍵情境為有意義與統整的形式」的需求高低，也就是將特定情境轉化為個人系統的需求，此需求強度是因人而異（周惠珍，1999）。

----上:原版 下:修改

認知需求動機最早為Wolf(1955)等人提出的概念，探討個人需要理解知識的內在動機歷程。Cacioppo(?)認為高認知需求的人喜歡思考的歷程，想要儘可能理解能解答眼前問題的各種資訊，合理推測認知需求越高的人越會採取行動從不同的管道獲取資訊，並且會認真判斷資訊的真實度。認知需求的概念進一步在需要理解特定資訊的情境中，發展為各式研究主題，像是能提高認知需求的廣告訊息設計(Zhang and Buda, 1999)。[周惠珍(1999)的研究主題？]

[說明 @cacioppoEfficientAssessmentNeed1984 設計的問卷項目如何建構認知需求動機的量測]





## 國內使用認知需求問卷的研究狀況:


1. 首先先說明使用了什麼研究



國內使用認知需求問卷的研究狀況:

過去的研究發現國內對於認知需求的研究有許多篇幅偏向行銷與廣告。而在國內認知需求問卷使用，有經由文獻回顧發現國內認知需求量表中譯版高泉豐(1994)，並透過瀏覽後證實此份針對問卷改良的文獻是Cacioppo(1984)的中譯版本，也在不少國內認知需求主題的相關研究被使用。另外在本重製研究透過文獻回顧找出國內外研究也有使用Cacioppo(1984)、高泉豐(1994)。

(高泉豐做了什麼，可能要再回去回顧)


認知需求相關主題的文獻:

目前台灣著手於認知需求與新冠疫情的研究，仍然還正在萌芽，是個未開發的新領域。目前與認知需求有相關的主題，國內偏向以行銷與廣告為主要篇幅。
國內對於認知需求主題相關的文獻涉及消費者以及廣告方面，廣告的介入(曾忠蕙， 王又鵬，民國95年)，將行銷手法中小額建構方式以及總額建構方式的行銷手法呈現於商品中。對於消費者而言「小額建構方式下所貶值的損失金額比較小」，研究結果發現小額建構方式更使消費者買單，研究將認知需求當作中介考量。發現消費者的認知需求程度會影響購買行為。雖然並未與資訊解讀主題相關，因此比較沒有與原研究Boot(2021)上的假設有什麼關聯探討。也許認知需求與資訊解讀的研究，目前在國內還沒有發展，可能會是未來探討認知需求研究的其中一種方向。

國外認知需求的主題:

認知動機與資訊解讀相關研究，Kaynar(2007)的研究結果發現高認知需求者使用互聯網的信息服務高於低認知需求者。與Boot(2021)同樣都有將認知需求(need for cognition)用於研究。Kaynar(2007)可以知道研究者在意的是認知需求者使用網站的意圖，而Boot(2021)，則是透過疫情爆發後，社會媒體使用的頻率，所以兩者討論的對象相同，不過所要看見的依變項結果，有不一樣的層面。




國外認知動機與資訊解讀相關研究:

  對於認知Kaynar(2007)研究探討認知需求程度與互聯網信息使用，研究結果發現高認知需求者的使用互聯網信息服務高於於低認知需求者。且高認知需求者透過皮爾森相關分系，得知更傾向於專業服務的信息。與同樣考量認知需求的原研究Boot(2021)，在研究結果的方向上有很大的不同，Kaynar(2007)，研究結果在意的是使用互聯網的動機，而Boot(2021)則探討認知需求程度與使用媒體資訊的管道以及頻率。兩個研究的共通點則是，皆屬於了解認知與使用網路，將認知需求以及社交媒體運用於研究。
  對於高認知需求者而言，他們思考時注重思考歷程。而專業信息的網站，更能夠讓他們學習以及獲取知識。Boot(2021)也提及高認知需求者更傾向理解不同的疫情資訊，在媒體使用上，或許兩者同樣都以認知需求角度出發，而因不同假設設定，使得研究結果呈現了可以綜合認知需求與資訊的研究成果。讓我們有一個對認知需求的人有一個初步的概念，他們傾向於理解資訊，以及因為喜歡思考，而在資訊快速的時代，網路變成他們快速獲取知識的媒介，也使得這些人使用資訊媒體的動機有別於其他人。
  
  
  
----上:原版 下:修改

高泉豐(1994)由於有參與最初版本的認知需求問卷開發(Cacioppo等人,1984)，採用相同的構念與研究方法建立中文版常模，也成為台灣學術界研究認知需求的各領域研究者，最常使用的測量工具。例如曾忠蕙，王又鵬(1996)比較兩種廣告行銷手法的效果，並且評估認知需求做為中介變項如何影響購買行為。網路平台逐漸成為一般人獲取資訊的主要管道之後，國內外學者均有探討認知需求如何調節所關心的目標行為。例如[(陳佳誼 & 柯書婷, 2016) ... ]。Kaynar(2007)發現高認知需求者比低認知需求者更容易接受網路服務，並且更傾向透過網路取得專業資訊與服務。



(討論Boot等人的假設未獲得假設支持的可能原因)

>>>>>> d00cf35..a7ec506
> Prolific平台的多數參與者年輕(20y\~40y)，會主動吸收最新資訊。

Boot原本H1b假設認為低NC比高NC者，他們顯示出較低的 COVID-19 信息更新頻率
Boot(2020)參與本研究的年齡介於20~40歲。在媒體使用方面，除了在家人與朋友的使用達到將近93%的高度使用情形。參與者在新聞網站回應的情形也達到將近90%，而在社交網站上的使用也達到將近82%。從數據上我們可能看見這些參與者普遍無論NCC.NC高低與否，同樣都有傾向主動透過社交網絡來得到疫情資訊。而傳統媒體以及無線電廣播沒有參與者使用的情形，可能與時代變化使用媒介獲取資訊管道有關。有可能因為參與者大多為20歲上下的成人，隨時能夠透過手機等3C電子產品獲得最新資訊，間接使得沒有什麼參與者透過報章雜誌，需要校稿並印刷的方式，更能透過網頁資訊獲取資訊，也是符合現代人的生活習慣。

>>> a7ec506..ba5dbe8

--> 在附錄A 基本個人資料裡，未能從描述統計確認參與者實際的年齡，但是可以從參加者的職位來看大部分為學生以及從事教育或是科技方面的參與者，參與者水平也有過半達到大學畢業(含)，因此推論參與者年齡層介於20~40之間。
(人口統計已經被學者拿掉了)




-----
 更新計畫書研究假設整理與研究結果
 







**國外認知需求與媒體使用相關研究:

目前尚未進行，先尋找國內有使用網路行為與認知動機的研究。




