---
title: 'My note'
author: "張祥偉"
date: "2021/9/2"
bibliography: Plain_lang_summary.bib
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#緒論
隨著時代的進步，學術研究每一年都有成千上萬篇出版，在許多的論壇或是網路影片，都會使用期刊文章作為佐證他們所提出的相關證據，透過第三人來轉述他們所找到的期刊文章，有時很難辨識內容是否有還原原作者的目的，如果在學術研究沒有經過專業訓練，或是大量閱讀，對於一般人而言並不是容易就能抓到原作者想表達的真正意思，所以白話文摘要之所以被如此重視，也是能夠讓一般人也能明白原作者的目的。

#文獻回顧
以概念構圖為教學策略提升學生科技論文閱讀能力[@xiongjingminYiGaiNianGouTuWeiJiaoXueCeLueTiShengXueShengKeJiLunWenYueDuNengLi2010]
該文獻指出，使用Novak(1988)提出概念構圖的閱讀技巧，有助於提升一般人的閱讀能力，在1991年提出閱讀的四種結構分別為1.關係。2.階層。3.交叉連結。4.舉例。於是研究者們想利用這套的閱讀技巧去了解該方式是否能有助於大學生的閱讀新事物的理解，參與者
為機械系大三學生，研究人員準備物理氣相沉積理論讓學生們經過一學期的實驗過程，成績是否會有所進步，實驗過程為：教學實施階段(共18週，扣除前後測進行6篇文獻閱讀，並教導概念構圖的閱讀理論)、前側(第一週閱讀文獻，隔一周寫題目)、後側(第十八週測驗題目)。結果為概念構圖對於大學生在閱讀文獻上成績有明顯提升。而高分組(為整體的前27%)與低分組(為整體的後27%)，低分組在前後測有明顯的成績進步。而低分組的學習態度上明顯高過於高分組，原因在於低分組認為概念構圖的方式，是有助於他們的閱讀理解。


##Kerwer等人的PLS研究
[@stollPlainLanguageSummaries2021]
Stoll et al.(2021)的研究中想探討PLS既定標準，以及用途，Kerwer等人對於PLS認為有四個重點1.目標（著重於非專業人士對於摘要的理解）2.特徵（語言上的使用是否接近該閱讀者母語）3.標準（避免使用太過於專業術語）4.結果(知識的測試了解非專業人士知識的獲取)。在第一點的目標上我們所重製研究原始論文中，比較重視。因為我們重製的對象是一般人在閱讀PLS上的適讀性。其餘的重點在重製研究中沒有過多的討論。Kerwer等人認為一個PLS要符合三個標準分別為1.是已發表科學證據的摘要。2.PLS的目標是非專業讀者。3.PLS使用與原始摘要相同的通信格式(Stoll et al.,2021) 。在白話文Kerwer這篇文獻雖然比較晚出現，但是對於重製研究上是很好的價值，盡管我們重製研究中對於PLS上我們並沒有太多限制，但是會去思考該如何把閱讀白話文摘要的重要性給顯現出來。

##
[luozhengjiaTaiWanDaXueShengYueDuXueShuYingWenHouSheRenZhiBianHuaZhiGeAnYanJiuYiBeiDongYueDuYingWenJiaoKeShuZheWeiLi2019]
以台灣的大學生為樣本閱讀英文文獻的研究並不常見，對於台灣大學生而言，英文是第二語言，沒有任何學術經驗，在閱讀英文文章，其挑戰性是相當困難。羅正佳(2019)的研究，他引用Huang(2006)說法，認為目前大部分對於讀者對於第二外語的閱讀上的研究，比較著重於探討讀者本身動機、焦慮情緒與閱讀策略。在羅正佳(2019)這篇研究上，以一位台灣大學生作為個案，研究個案閱讀第二外語的英文文獻的態度如何從被動提升積極。閱讀策略上主要採取設認知閱讀進行，後設認知閱讀(Matacognitive reading)是讀者需要自己閱讀的目的，以及如何達成，在Baker&Brown(1984)研究結果為，讀第二外語閱讀者都會詢問有沒有達到閱讀的目標。

##緒論
可讀性研究
原研究使用Mc Laughlin(1969)提出的可讀性指標-SMOG，作為原研究實驗材料的判斷標準，原研究的學術摘要SMOG比白話文摘要SMOG還高，表示為學術摘要較難理解，SMOG的判斷標準為數值越小，代表內容比較好讀，該指標發展至今已相當成熟，英文文獻可讀性指標不只有SMOG這類型的工具，隨著時代的進步越來越多的可讀性指標也相對出現判斷文章的可讀性，在中文文獻中目前有類似的可讀性指標由宋曜廷(2013)團隊提出CRIE可讀性指標，該指標主要分為四類，為詞彙類指標、語意類指標、句法類指標、文章凝聚性指標。CRIE相關研究不多，2020年宋曜廷等人探討國小教課書程度是否符合該年級的閱讀程度，透過人工判讀與CRIE可讀性分析系統判讀是否一致，透過這個能知道CRIE用的範圍很廣，但比較少看到CRIE是使用在學術性質文獻裡。


##10/6討論重點
1.假設後面談論，為何可讀性因白話摘要與學術摘要的差異，因為中文還需要有像英文一樣客觀的指標，稍微提出SMOG在英文學術研究界重要性。
2.從KERWER一系列的研究，可以比較我們與他們的差別。KERWER的研究對於學術界重視白話文摘要應用的貢獻。
3.中文與英文摘要目的是不同，但KERWER的研究結果可以證明不管是否為英文，對於科學價值效益是提高的。
4.找KERWER比較學術與白話文摘要文獻做回顧。



# 研究方法
---
## 研究材料
學術摘要取自於《中華心理學刊》中發表的期刊論文，白話摘要取自於中華心理學刊網站中「心理學任意門」的專欄文章，並加入副標題，成為有標題的白話文摘要，加入的副標題分別為背景、為什麼進行這項研究、研究人員做了什麼和發現了什麼與這些發現意味著什麼，並與原作者確認設計的白話文摘要是否與原論文相符以及副標題的設計是否需要修改。全部共設計了14篇，經詢問原作者過後，有2篇因作者私人因素而不予使用，最後可用摘要為12篇，也對各個摘要進行中文文本可讀性指標自動化分析。

知識理解測驗為針對摘要的內容回答是或否的問題。與原始研究不同的是，原始研究設計了24題，是學術摘要與白話摘要各一題，總共24題，而其中有14題為正向題，10題為反向題，而我們則是每一種摘要皆有正向與反向題，並使用隨機分配的方式，並控制亂數讓參與者回答到正向題皆近14題（58%）反向題10題（42%），進行測驗時會從該摘要題目中隨機挑出正向或反向題，用於測量知識獲取量。

## 研究程序
參與者的條件為在台灣地區公立或私立之一般大學學籍的在學學生，中文理解能力佳者，招募方法透過FACEBOOK、Instergram、Dcard、PTT等各大網路論壇招募、數據蒐集的日期為2021年11月1日開始至2022年4月30日截止。網路化問卷使用OSWEB 1.4 製作，經由JATOS伺服器部署[@langeJustAnotherTool2015; @mathotOpenSesameOpensourceGraphical2012]。確認同意參與研究的受測者，首先回覆性別、出生年份等基本人口統計資料。接著回覆改編自Kewer等人(2021)的兩份前置問卷：包括有關心理科學知識權威認知的9個問題[@bratenJustificationBeliefsMultipledocuments2013]，以及科學活動熟悉度的兩個問題。接著逐篇閱讀十二篇摘要，以及回答可理解性、科學性、可信度、可參考度、內容充分度、還有是否需要觀看全文等六項讀後問題。每讀過三篇摘要之後，接著回答相關文本的各兩道知識理解測驗題。十二篇摘要的順序與呈現版本皆隨機呈現，可理解性、科學性、可信度、可參考度、內容充分度等五個問題以8個等級選項，代表受測者對一篇摘要在這些向度的認同程度；是否需要觀看全文的問題是詢問受測者要不要索取全文下載連結，回答「要」就會呈現連結網址。每個段落最後呈現的六道知識理解測驗題為是非題，題目以隨機順序呈現，所有是非題答案比照Kewer等人的設計，有14題的正確答案為「是」，10題的正確答案為「否」, 正確答案的配置以隨機程序決定。每個段落之後有一次強制90秒的休息時間，直到最後一個段落結束為止。

# 變項
操縱變項
- 有標題的白話文摘要
- 沒有標題的白話文摘要
- 學術摘要

非操縱變項
- 心理科學知識權威認知

依變項
根據獨變項的三種不同摘要，看是否影響這些依變項變化。

- 1.「對於摘要的理解」 (次序尺度) 
- 2.「感知的摘要科學性」(次序尺度) 
- 3.「對於研究的信用」(次序尺度)
- 4.「獲取文章來源的意願性」（名目尺度）
- 5.知識理解測驗「是非題，對於該文章的測驗，測量知識獲取量」（名目尺度）
1. 48 題
1. 2 種版本(學術版本與白話版本) 
1. 24 題正向題, 24題反向題 
- 6.感知對自己評估研究能力的信心
- 7.對交叉評估的感知需求