---
title: 'My note'
author: "林子渝"
date: "2021/9/2"
bibliography: Plain_lang_summary.bib
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 將心理學整合分析的證據翻譯成通俗易懂的語言

Kerwer後續的研究，在於設計出一個指南，用一個標準的方法使學術摘要寫成一個好的白話文摘要，這種指南在生物醫學上已經廣泛使用。在該項研究的預印本中，他們設計了幾個變項，區分各種PLS，例如有無副橿題區分段落、對統計術語的解釋與研究設計的複雜性等等。[@kerwerTranslatingEvidencePsychological2021]

### 科普文章的簡易效應（Easiness Effect）與白話文摘要

在現代的多媒體時代，有越來越多的創作者使用各種方法包裝自己的作品，除了最一開始的純文字文章，也加入圖文並貌的圖文，或是用影音的方式呈現，發佈於各大社交平台中，像是FB、IG、Youtube或Podcast等。而其中不乏有關於科學性專業知識的科普內容分享，例如：PanSci泛科學、佑來了、蒼藍鴿的醫學天地、三個字 SunGuts、哇賽心理學、心理敲敲門等等，可以使觀眾與聽眾以更簡單輕鬆的方式去了解到相關領域的知識並勾起大眾對其科學的興趣。而其中內容的可信度也會被大眾公開檢視，除了有些創作者本身具有該領域的專業證照外，有些也會在附註的地方加入引用的文獻或資料來源來提高公信力，而如何從幾篇的文獻中濃縮出重點與使大眾淺而易懂的資訊則各憑本事了。
根據簡易效應，也就是科普文章使外行人對科學知識產生過度自信的理解，這導致科學相關的決策反映了對科普的誤解，而不是專業科學家的判斷。而訊息以愈容易理解的方式呈現，一般人會愈認為訊息是對的並相信其知識主張，所以進行科普時，資訊的可信度與正碓性是一個很重要的面向，在2020年11月，知名Youtuber愛莉莎莎在影片中分享肝膽排石法，因內容有誤會誤導觀眾而遭各大專業人事的指責，事後愛莉莎莎也下架影片公開道歉，由此可見在科普資訊的路上是需要專業人事把關的，這也突顯了白話文摘要的重要性。

## 可讀性分析

在文本分級的研究中常使用可讀性分析，主要是使用詞長、字詞等當作指標，在原始研究中使用的是可讀性分析為SMOG，SMOG在國外以有長久的歷史與充分的研究，已被用於評估訊息材料、教育材料與心理測量工具上，是一個具有公信力的分析工具，在原研究團隊先前的研究中，以有發現PLS比學術摘要更好閱讀，並且在可讀性指數中也得到了復制[@strickerScientificAbstractsPlain2020]。而在國內，中文文本的可讀性指標尚在發展中，本研究使用的是宋曜廷教授團隊開發的文本可讀性指標自動化分析系統，主要是用在學生教材文章的分級上，雖然該團隊已開發到第三版，但在學術界中使用此項工具做研究的論文並不多，本次用於期刊文獻的摘要上也是一大挑戰。而在本研究的適可讀性分析分數的比較上，沒有太大的差異，在第一版的分數與第二版的分數也有分歧，這是本研究有所限制的部份。

## 適讀性分析

適讀性分析也是文本分級研究中使用的分析方法，適讀性分析取向所包含的更加全面，除了原本的難詞、句長等，還考慮了內容、觀點、印刷等要素，雖然適讀性分析缺乏客觀性質的判斷與標準，但在閱讀與理解上還是有它的重要性。[@chenrulingWenBenShiDuXingFenJiJiaGouZhiJianLiYanJiu2015]
李茹玲的研究指出，在中文的適讀性中最重要的是內容其次是語言與文學，內容的要素有概念、主題與主旨、觀點，而語言與文學則包含字與詞、句與段落、文學，在這些要素中有許多與副標題的設計息息相關，像是主旨、觀點、句與段落，有了副標題這些要素都會更加明瞭，而沒有副標題的PLS可能就會跟學術摘要的難易度沒有太大的差別，這也可能是原始研究沒有考慮到的地方。

## 重製研究問題與假設

1. "Plain language summary vs. Ordinary abstract" on comprehensibility & knowledge and knowledge acquisition  
2. "Plain with sub-heading vs. Plain without sub-heading" on comprehensibility & knowledge and knowledge acquisition  
3. Easiness effects: Credibility, Confidence to evaluate, Need for cross-evaluation

原研究中提出了兩種假設方向，分別是確認性假設與探索性假設，本重制研究在確證性假設的部分與原假設一致，而探索性假設只重制其中一項獲取全文意願性，會做如此的篩選有幾點原因，主要是因為確認性假設為本研究探討的重點，其次是探索性假設中，原研究討論認知情緒、獲取全文意願性、辯護信念與英文能力的作用，英文能力在本研究中不適用，因為我們閱讀的摘要為參語者母語，並不用檢測語文能力，所以予以排除，而認知情緒與辯護信念的統計分析方法不在本研究者的能力範圍內，最後留下獲取全文意願性。

### 簡易效應的確證性假設

H1. 有標題的白話文摘要、沒標題的白話文摘要比學術摘要，參與者認為更容易理解(comprehensibility)。
H2. 有標題的白話文摘要比沒標題的白話文摘要、學術摘要，參與者更能有效吸收知識(knowledge acquisition)。
H3a. 有標題的白話文摘要比學術摘要，參與者認為可信度更高(Credibility)。
H3b. 沒有標題的白話文摘要比學術摘要，參與者認為可信度更高(Credibility)。
H4a. 有標題的白話文摘要比學術摘要，參與者認為更能評估研究內容的真實性(Confidence to evaluate)。
H4b. 沒有標題的白話文摘要比學術摘要，參與者認為更能評估研究內容的真實性(Confidence to evaluate)。
H5a. 有標題的白話文摘要比學術摘要，參與者傾向認為不需要更多資訊才能理解內容(cross-evaluation)。
H5b. 沒有標題的白話文摘要比學術摘要，參與者傾向認為不需要更多資訊才能理解內容(cross-evaluation)。

H1到H5的假設中皆涉及到摘要材料的限制，本研究所處的學術環境中，並無原作者親自撰寫白話文摘要，這對於重製研究上是很大的限制，而Kerwer團隊中所選用的摘要材料則是原論文作者親自撰寫且符合該期刊的固定格式，在研究材料選取上，為了本研究使用的研究材料逼近Kerwer團隊選用的材料，本研究從「中華心理學刊」網站中的專欄文章做篩選，加入合適的副標題形成有標題的白話文摘要，並與原作者連繫，以確認使用的文本並無扭曲原始論文的原意。

在H2中，本研究對測驗吸收知識的知識理解測驗題做更嚴謹的設計，原始研究設計了24題，全部12篇摘要學術摘要與白話摘要各一題，總共24題，而其中有14題為正向題，10題為反向題；本研究則是12篇摘要皆設計正向與反向題，並使用隨機分配的方式，並控制亂數參數讓參與者回答的題目中皆近14題（58%）正向題，反向題10題（42%），進行測驗時會從該摘要題目中隨機挑出正向或反向題。
在H3的限制中，Kerwer團隊在來源可信度上都是來自同一處，本研究則是學術摘要來自中華心理學刊，而白話文摘要是來自於中華心理學刊的心理學任意門。

在原研究假設H3b、H4b、H5b則沒有得到充分支持。Kerwer團隊認為參與者在閱讀文本內容並不是自己有興趣的文本，進而影響閱讀上的表現[@kerwerStraightScientistMouth2021]。
原研究文獻所涵蓋的主題為社會與政治相關的心理學文章，為了提升參與者在閱讀文章上的興趣，我們去除政治心理學範圍的文章，加入其他主題的心理學文章。白話文摘為了使內容較易閱讀，通常篇幅會較長去解釋專有名詞，以較簡單的方式去描述該研究的進行，而去除標題也就意為著沒有段落，會變成一大段攏長的文章，在文本適度性中，字詞數、行數與段落皆為適讀性的指標[@chenrulingWenBenShiDuXingFenJiJiaGouZhiJianLiYanJiu2015]。

### 簡易效應的探索性假設

在原始研究的調查中，參與者要求獲取全文的有17.21%，有標題的白話文摘要為18.23%，沒有標題的白話文摘要為18.25%，而學術摘要為15.21%較低，可見在參與者在觀看白話文摘要時更可以勾起他們想獲取全文的意願。[@kerwerStraightScientistMouth2021]在勾起參與者獲取全文的興趣時，也代表著參與者對心理學知識產生好奇，這也是做科普文章所樂意所看到的，有了好奇心就會有求知慾，從全文中得到更深入的知識，使科學更貼近社會大眾，也可以減少對心理學相關知識的偏見與污名。

## 科普文章書籍與白話文摘要需求

在博客來的書藉分類中，就有一類分類是「其他大眾心理學」，書目共有206本，主要就是以較簡單、白話的口吻來闡述心理學的知識與論點，例如：《趣味心理學原來是神隊友：10秒鐘人生助攻教室》、《哇賽！心理學：48個超實用建議，讓你從此告別卡卡人生》、《簡單心理學：職業倦怠、社交障礙、難忘舊愛……你心態崩壞了嗎？》，而使用白話、科學為關鍵字搜尋，也可以找到許多科普的網頁、專欄或書藉，由此可見大眾對科普書藉的需求，對此做文章的作者也有其市場，以更多元的方式宣傳科普的知識。

## 分析計畫

我們使用與原研究相同的混合效果模型來分析數據，全部假設皆使用相同的混合效果模型，唯一的不同是依變項。隨機效果因素是12篇摘要文本和參與者。獨變項為三種摘要類型變項。
對應研究假設1至5的依變項依序為：對於摘要的理解性、知識獲取量、對於研究的可信度、察覺自己評估研究能力的信心、對需要更多資訊的決策能力。




### 白話文摘要的簡易效應（Easiness Effect）
2021
變項加入與自己的信念與自己一致不一致，可以放在討論或補充。

簡易效應讓學者好奇，如果讀者先有定見，摘要的閱讀難易度會不會改變讀者對議題的看法。 @scharrerInformationEasinessAffects2021取用討論氣候變遷原因的科學文章，透過事先調查參與者信念，以及調整科學文章的難易度，發現簡易效應會影響參與者對他們持有先前信念的科學主張判斷，會傾向同意簡單的文章，並覺得簡單來源文章的來源更加可信，但前提是符合他們先前的信念，若訊息與先前的信念不符合，參與者會在評估中缺乏安全感，並增加諮詢專家的意見。他們也發現無關文章的難易度，只要文章與他們的信念不一致，參與者就不會同意這種說法，也不會認為來源是可信的。這會使非專家高估自己的評估能力，易於去理解相信錯誤的簡單訊息，他們也觀注到這種簡化描述會被當作政治訊息的一種手段，以易於理解的主張與解決方案來吸引選民。
本研究與原研究相同預期簡易效應會影響白話文摘要，由上述的研究結果可以看出先前信念會大大引響對於可信度、真實性與評估能力的看法，這幾點對應了原研究假設3、4、5，所以有關心理科學知識權威認知的問題尤為重要。

### Scharrer 2017

先提全部假設，再看為什麼可以對應kerwer的假設，
描述如何接到kerwer 的研究
確認性假設再描述

該研究提出了4項假設，分別為H1a閱讀非專業文章會讓外行評估訊息更可信，H1b閱讀非專業文章比起專業文章會讓外行更同意他們的知識主張，H2a閱讀了非專業文章後外行更相信自己現有的知識判斷，H2b閱讀了非專業文章後更相信獲得更多內容信息後的自己的判斷，H2c閱讀了非專業文章後表現出較弱的向知識淵博的人諮詢的期望，H3外行人閱讀非專業文章後，認為自己的主題知識更廣泛，H4a閱讀非專業文章會導致外行認為該主題不那麼複雜，H4b閱讀非專業文章會導致外行認為該主題較少爭議。
該研究區分專業與非專業的材料為給專家觀看的科學雜誌與一般的小報雜誌，內容為醫學相關的報導，研究結果發現支持假設H1a、H1b、H2a，H2c。而kerwer針對這幾個假設上做週整，合併H1a、H1b形成他們研究的假設H3有標題的白話文摘要比學術摘要，參與者認為可信度更高，H2a為假設H4有標題的白話文摘要比學術摘要，參與者認為更能評估研究內容的真實性，H2c為假設H5有標題的白話文摘要比學術摘要，參與者傾向認為不需要更多資訊才能理解內容。並且文章資料從雜誌換為更嚴謹的論文摘要，白話文摘要對應一般的小報雜誌，學術摘要對應給專家觀看的科學雜誌。

在一般的文章中已經可見簡易效應的效果，kerwer的研究接續了這幾項假設，想要研究簡易效應在論文摘要上的效果，在獨變項的設計上一樣控制了文本上的可讀性做區分，主要還是著重於調查可信度、真實性與做決定這三個面向，

重制莎利的更複雜，要孝慮的更多，所以重制可沃的，->解釋。
拿掉NCC測謊題，聨絡假新聞清潔劑有沒有可以接觸老人的團體
